// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { AdmState, isAdmState } from './AdmState';

export interface AdmConfig {
  state: AdmState;
}

export function isAdmConfig(v: any): v is AdmConfig {
  return v['state'] && isAdmState(v['state']);
}
