// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { AdmissionState, isAdmissionState } from './AdmissionState';
import { Error, isError } from './Error';

export interface AdmissionStateWrap {
  state: AdmissionState;
  error?: Error;
}

export function isAdmissionStateWrap(v: any): v is AdmissionStateWrap {
  return (
    (v['state'] && isAdmissionState(v['state'])) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
