// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface AdmissionRulesWrap {
  rules: Array;
  error?: Error;
}

export function isAdmissionRulesWrap(v: any): v is AdmissionRulesWrap {
  return (
    (v['rules'] && isArray(v['rules'])) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
