// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface AdmissionRule {
  id: number;
  critical: boolean;
  disable: boolean;
}

export function isAdmissionRule(v: any): v is AdmissionRule {
  return (
    typeof v['id'] === 'number' &&
    typeof v['critical'] === 'boolean' &&
    typeof v['disable'] === 'boolean'
  );
}
