// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface AdmissionState {
  enable: boolean;
}

export function isAdmissionState(v: any): v is AdmissionState {
  return (
    ((typeof v['enable']) === 'boolean')
  );
}
