// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class AdmissionJsonProtocol {
  private static instance: AdmissionJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!AdmissionJsonProtocol.instance) {
      AdmissionJsonProtocol.instance = new AdmissionJsonProtocol();
    }

    return AdmissionJsonProtocol.instance;
  }
}

export const AdmissionJsonProtocolInhabitant: AdmissionJsonProtocol =
  AdmissionJsonProtocol.getInstance();

export function isAdmissionJsonProtocol(v: any): v is AdmissionJsonProtocol {
  return (
    v instanceof AdmissionJsonProtocol && v === AdmissionJsonProtocolInhabitant
  );
}
