// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface AdmRuleSubCriterion {
  name: string;
  op: string;
  value: string;
}

export function isAdmRuleSubCriterion(v: any): v is AdmRuleSubCriterion {
  return (
    typeof v['name'] === 'string' &&
    typeof v['op'] === 'string' &&
    typeof v['value'] === 'string'
  );
}
