// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface AdmRuleCriterion {
  sub_criteria?: Array;
  name: string;
  op?: string;
  value?: string;
}

export function isAdmRuleCriterion(v: any): v is AdmRuleCriterion {
  return (
    (!v['sub_criteria'] || (v['sub_criteria'] && isArray(v['sub_criteria']))) &&
    ((typeof v['name']) === 'string') &&
    (!v['op'] || ((typeof v['op']) === 'string')) &&
    (!v['value'] || ((typeof v['value']) === 'string'))
  );
}
