// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { AdmRule, isAdmRule } from './AdmRule';

export interface AdmRuleConfig {
  config: AdmRule;
}

export function isAdmRuleConfig(v: any): v is AdmRuleConfig {
  return (
    (v['config'] && isAdmRule(v['config']))
  );
}
