// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class AlertJsonProtocol {
  private static instance: AlertJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!AlertJsonProtocol.instance) {
      AlertJsonProtocol.instance = new AlertJsonProtocol();
    }

    return AlertJsonProtocol.instance;
  }
}

export const AlertJsonProtocolInhabitant: AlertJsonProtocol = AlertJsonProtocol.getInstance();

export function isAlertJsonProtocol(v: any): v is AlertJsonProtocol {
  return (v instanceof AlertJsonProtocol) && (v === AlertJsonProtocolInhabitant);
}
