// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ApplicationAnalysis {
  count: number;
  totalBytes: number;
}

export function isApplicationAnalysis(v: any): v is ApplicationAnalysis {
  return typeof v['count'] === 'number' && typeof v['totalBytes'] === 'number';
}
