// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ApplicationList {
  application?: string;
}

export function isApplicationList(v: any): v is ApplicationList {
  return !v['application'] || typeof v['application'] === 'string';
}
