// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ApplicationsInPolicy {
  id: number;
  from: string;
  to: string;
  applications: Array;
}

export function isApplicationsInPolicy(v: any): v is ApplicationsInPolicy {
  return (
    ((typeof v['id']) === 'number') &&
    ((typeof v['from']) === 'string') &&
    ((typeof v['to']) === 'string') &&
    (v['applications'] && isArray(v['applications']))
  );
}
