// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface ApplicationsInPolicyWrap {
  rules: Array;
  error?: Error;
}

export function isApplicationsInPolicyWrap(
  v: any
): v is ApplicationsInPolicyWrap {
  return (
    v['rules'] &&
    isArray(v['rules']) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
