// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Password, isPassword } from './Password';

export interface AuthRequest {
  password: Password;
  client_ip: string;
}

export function isAuthRequest(v: any): v is AuthRequest {
  return (
    v['password'] &&
    isPassword(v['password']) &&
    typeof v['client_ip'] === 'string'
  );
}
