// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { None, isNone } from './None';
import { scala, isscala } from './scala';

export class AuthenticationManager {
  public token: None = scala.None;

  private static instance: AuthenticationManager;

  private constructor() {}

  public static getInstance() {
    if (!AuthenticationManager.instance) {
      AuthenticationManager.instance = new AuthenticationManager();
    }

    return AuthenticationManager.instance;
  }
}

export const AuthenticationManagerInhabitant: AuthenticationManager = AuthenticationManager.getInstance();

export function isAuthenticationManager(v: any): v is AuthenticationManager {
  return (v instanceof AuthenticationManager) && (v === AuthenticationManagerInhabitant);
}
