// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface AutoScan {
  auto_scan: boolean;
}

export function isAutoScan(v: any): v is AutoScan {
  return (
    ((typeof v['auto_scan']) === 'boolean')
  );
}
