// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface AWSAccount {
  id: string;
  access_key_id?: string;
  secret_access_key?: string;
  region: string;
}

export function isAWSAccount(v: any): v is AWSAccount {
  return (
    typeof v['id'] === 'string' &&
    (!v['access_key_id'] || typeof v['access_key_id'] === 'string') &&
    (!v['secret_access_key'] || typeof v['secret_access_key'] === 'string') &&
    typeof v['region'] === 'string'
  );
}
