// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ClusterSwitched {
  id?: string;
}

export function isClusterSwitched(v: any): v is ClusterSwitched {
  return !v['id'] || typeof v['id'] === 'string';
}
