// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class ClusterJsonProtocol {
  private static instance: ClusterJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!ClusterJsonProtocol.instance) {
      ClusterJsonProtocol.instance = new ClusterJsonProtocol();
    }

    return ClusterJsonProtocol.instance;
  }
}

export const ClusterJsonProtocolInhabitant: ClusterJsonProtocol = ClusterJsonProtocol.getInstance();

export function isClusterJsonProtocol(v: any): v is ClusterJsonProtocol {
  return (v instanceof ClusterJsonProtocol) && (v === ClusterJsonProtocolInhabitant);
}
