// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface CLUSEventCondition4Group {
  type: string;
  value: string;
}

export function isCLUSEventCondition4Group(
  v: any
): v is CLUSEventCondition4Group {
  return typeof v['type'] === 'string' && typeof v['value'] === 'string';
}
