// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface CLUSEventCondition {
  type: string;
  value: string;
}

export function isCLUSEventCondition(v: any): v is CLUSEventCondition {
  return typeof v['type'] === 'string' && typeof v['value'] === 'string';
}
