// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ClusterServer, isClusterServer } from './ClusterServer';

export interface ClusterConfig {
  config: ClusterServer;
}

export function isClusterConfig(v: any): v is ClusterConfig {
  return (
    (v['config'] && isClusterServer(v['config']))
  );
}
