// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ClusterServer {
  name: string;
  id: string;
  api_server: string;
  api_port?: number;
  status?: string;
  username?: string;
}

export function isClusterServer(v: any): v is ClusterServer {
  return (
    typeof v['name'] === 'string' &&
    typeof v['id'] === 'string' &&
    typeof v['api_server'] === 'string' &&
    (!v['api_port'] || typeof v['api_port'] === 'number') &&
    (!v['status'] || typeof v['status'] === 'string') &&
    (!v['username'] || typeof v['username'] === 'string')
  );
}
