// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ClusterServerInfo {
  server: string;
  port: number;
}

export function isClusterServerInfo(v: any): v is ClusterServerInfo {
  return (
    ((typeof v['server']) === 'string') &&
    ((typeof v['port']) === 'number')
  );
}
