// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class ComplianceJsonProtocol {
  private static instance: ComplianceJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!ComplianceJsonProtocol.instance) {
      ComplianceJsonProtocol.instance = new ComplianceJsonProtocol();
    }

    return ComplianceJsonProtocol.instance;
  }
}

export const ComplianceJsonProtocolInhabitant: ComplianceJsonProtocol =
  ComplianceJsonProtocol.getInstance();

export function isComplianceJsonProtocol(v: any): v is ComplianceJsonProtocol {
  return (
    v instanceof ComplianceJsonProtocol &&
    v === ComplianceJsonProtocolInhabitant
  );
}
