// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ComplianceProfile, isComplianceProfile } from './ComplianceProfile';

export interface ComplianceProfileData {
  profile: ComplianceProfile;
}

export function isComplianceProfileData(v: any): v is ComplianceProfileData {
  return v['profile'] && isComplianceProfile(v['profile']);
}
