// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ComplianceProfile {
  name: string;
  disable_system: boolean;
  entries: Array;
}

export function isComplianceProfile(v: any): v is ComplianceProfile {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['disable_system']) === 'boolean') &&
    (v['entries'] && isArray(v['entries']))
  );
}
