// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class Constant {
  public waitingLimit: number = 60;

  private static instance: Constant;

  private constructor() {}

  public static getInstance() {
    if (!Constant.instance) {
      Constant.instance = new Constant();
    }

    return Constant.instance;
  }
}

export const ConstantInhabitant: Constant = Constant.getInstance();

export function isConstant(v: any): v is Constant {
  return v instanceof Constant && v === ConstantInhabitant;
}
