// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class ContainerConfigJsonProtocol {
  private static instance: ContainerConfigJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!ContainerConfigJsonProtocol.instance) {
      ContainerConfigJsonProtocol.instance = new ContainerConfigJsonProtocol();
    }

    return ContainerConfigJsonProtocol.instance;
  }
}

export const ContainerConfigJsonProtocolInhabitant: ContainerConfigJsonProtocol = ContainerConfigJsonProtocol.getInstance();

export function isContainerConfigJsonProtocol(v: any): v is ContainerConfigJsonProtocol {
  return (v instanceof ContainerConfigJsonProtocol) && (v === ContainerConfigJsonProtocolInhabitant);
}
