// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ContainerQuarantineRequest {
  id: string;
  quarantine: boolean;
}

export function isContainerQuarantineRequest(
  v: any
): v is ContainerQuarantineRequest {
  return typeof v['id'] === 'string' && typeof v['quarantine'] === 'boolean';
}
