// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Container {
  id: string;
  name: string;
  display_name: string;
  state: string;
  service: string;
  service_group: string;
}

export function isContainer(v: any): v is Container {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['display_name']) === 'string') &&
    ((typeof v['state']) === 'string') &&
    ((typeof v['service']) === 'string') &&
    ((typeof v['service_group']) === 'string')
  );
}
