// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { ScanBrief, isScanBrief } from './ScanBrief';

export interface ConversationEndpoint {
  id: string;
  name: string;
  display_name: string;
  state: string;
  kind: string;
  platform_role?: string;
  service_group?: string;
  domain: string;
  share_ns_with?: string;
  policy_mode?: string;
  scan_summary?: ScanBrief;
  cap_quarantine: boolean;
  cap_change_mode: boolean;
  cap_sniff: boolean;
  children?: Array;
}

export function isConversationEndpoint(v: any): v is ConversationEndpoint {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['display_name']) === 'string') &&
    ((typeof v['state']) === 'string') &&
    ((typeof v['kind']) === 'string') &&
    (!v['platform_role'] || ((typeof v['platform_role']) === 'string')) &&
    (!v['service_group'] || ((typeof v['service_group']) === 'string')) &&
    ((typeof v['domain']) === 'string') &&
    (!v['share_ns_with'] || ((typeof v['share_ns_with']) === 'string')) &&
    (!v['policy_mode'] || ((typeof v['policy_mode']) === 'string')) &&
    (!v['scan_summary'] || (v['scan_summary'] && isScanBrief(v['scan_summary']))) &&
    ((typeof v['cap_quarantine']) === 'boolean') &&
    ((typeof v['cap_change_mode']) === 'boolean') &&
    ((typeof v['cap_sniff']) === 'boolean') &&
    (!v['children'] || (v['children'] && isArray(v['children'])))
  );
}
