// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Container, isContainer } from './Container';

export interface ConversationBrief {
  from: Container;
  to: Container;
  bytes: number;
  severity?: string;
  policy_action: string;
}

export function isConversationBrief(v: any): v is ConversationBrief {
  return (
    v['from'] &&
    isContainer(v['from']) &&
    v['to'] &&
    isContainer(v['to']) &&
    typeof v['bytes'] === 'number' &&
    (!v['severity'] || typeof v['severity'] === 'string') &&
    typeof v['policy_action'] === 'string'
  );
}
