// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';
import { Domain, isDomain } from './Domain';

export interface ConvertedThreat {
  id: string;
  name: string;
  reported_timestamp: number;
  reported_at: DateTime;
  count: number;
  source_workload_id: string;
  source_workload_name: string;
  destination_workload_id: string;
  destination_workload_name: string;
  domain: Domain;
  severity: string;
  action: string;
  source_port: number;
  destination_port: number;
  source_conn_port?: number;
  destination_conn_port?: number;
  source_ip: string;
  destination_ip: string;
  application: string;
  target: string;
  cap_len?: number;
  message: string;
}

export function isConvertedThreat(v: any): v is ConvertedThreat {
  return (
    typeof v['id'] === 'string' &&
    typeof v['name'] === 'string' &&
    typeof v['reported_timestamp'] === 'number' &&
    v['reported_at'] &&
    isDateTime(v['reported_at']) &&
    typeof v['count'] === 'number' &&
    typeof v['source_workload_id'] === 'string' &&
    typeof v['source_workload_name'] === 'string' &&
    typeof v['destination_workload_id'] === 'string' &&
    typeof v['destination_workload_name'] === 'string' &&
    v['domain'] &&
    isDomain(v['domain']) &&
    typeof v['severity'] === 'string' &&
    typeof v['action'] === 'string' &&
    typeof v['source_port'] === 'number' &&
    typeof v['destination_port'] === 'number' &&
    (!v['source_conn_port'] || typeof v['source_conn_port'] === 'number') &&
    (!v['destination_conn_port'] ||
      typeof v['destination_conn_port'] === 'number') &&
    typeof v['source_ip'] === 'string' &&
    typeof v['destination_ip'] === 'string' &&
    typeof v['application'] === 'string' &&
    typeof v['target'] === 'string' &&
    (!v['cap_len'] || typeof v['cap_len'] === 'number') &&
    typeof v['message'] === 'string'
  );
}
