// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ConversationBriefWrap {
  conversations: Array;
}

export function isConversationBriefWrap(v: any): v is ConversationBriefWrap {
  return (
    (v['conversations'] && isArray(v['conversations']))
  );
}
