// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ConversationEndpointData {
  endpoints: Array;
}

export function isConversationEndpointData(
  v: any
): v is ConversationEndpointData {
  return v['endpoints'] && isArray(v['endpoints']);
}
