// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { WorkloadsStatus, isWorkloadsStatus } from './WorkloadsStatus';

export interface ConvertedScannedWorkloadsWrap {
  workloads: Array;
  status: WorkloadsStatus;
}

export function isConvertedScannedWorkloadsWrap(v: any): v is ConvertedScannedWorkloadsWrap {
  return (
    (v['workloads'] && isArray(v['workloads'])) &&
    (v['status'] && isWorkloadsStatus(v['status']))
  );
}
