// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface ConvertedDashboardSecurityEvent {
  policy_id?: number;
  name?: string;
  source_workload_id?: string;
  source_workload_name?: string;
  destination_workload_id?: string;
  destination_workload_name?: string;
  source_domain?: string;
  destination_domain?: string;
  level: string;
  host_name: string;
  source_port?: number;
  destination_port?: number;
  server_conn_port?: number;
  source_ip?: string;
  destination_ip?: string;
  application?: string;
  reported_at: DateTime;
}

export function isConvertedDashboardSecurityEvent(v: any): v is ConvertedDashboardSecurityEvent {
  return (
    (!v['policy_id'] || ((typeof v['policy_id']) === 'number')) &&
    (!v['name'] || ((typeof v['name']) === 'string')) &&
    (!v['source_workload_id'] || ((typeof v['source_workload_id']) === 'string')) &&
    (!v['source_workload_name'] || ((typeof v['source_workload_name']) === 'string')) &&
    (!v['destination_workload_id'] || ((typeof v['destination_workload_id']) === 'string')) &&
    (!v['destination_workload_name'] || ((typeof v['destination_workload_name']) === 'string')) &&
    (!v['source_domain'] || ((typeof v['source_domain']) === 'string')) &&
    (!v['destination_domain'] || ((typeof v['destination_domain']) === 'string')) &&
    ((typeof v['level']) === 'string') &&
    ((typeof v['host_name']) === 'string') &&
    (!v['source_port'] || ((typeof v['source_port']) === 'number')) &&
    (!v['destination_port'] || ((typeof v['destination_port']) === 'number')) &&
    (!v['server_conn_port'] || ((typeof v['server_conn_port']) === 'number')) &&
    (!v['source_ip'] || ((typeof v['source_ip']) === 'string')) &&
    (!v['destination_ip'] || ((typeof v['destination_ip']) === 'string')) &&
    (!v['application'] || ((typeof v['application']) === 'string')) &&
    (v['reported_at'] && isDateTime(v['reported_at']))
  );
}
