// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface CriteriaEntry {
  key: string;
  value: string;
  op: string;
}

export function isCriteriaEntry(v: any): v is CriteriaEntry {
  return (
    typeof v['key'] === 'string' &&
    typeof v['value'] === 'string' &&
    typeof v['op'] === 'string'
  );
}
