// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface CriticalSecurityEventDTO {
  top_violations: Error | TopViolation;
  top_threats: Error | TopThreat;
  summary: Error | { [key: string]: ReadonlyArray<[string, number]> };
  alertedContainers: Error | ReadonlyArray<string>;
}

export function isCriticalSecurityEventDTO(
  v: any
): v is CriticalSecurityEventDTO {
  return (
    ((v['top_violations'] && isError(v['top_violations'])) ||
      (v['top_violations'] && isTopViolation(v['top_violations']))) &&
    ((v['top_threats'] && isError(v['top_threats'])) ||
      (v['top_threats'] && isTopThreat(v['top_threats']))) &&
    ((v['summary'] && isError(v['summary'])) ||
      (typeof v['summary'] == 'object' &&
        Object.keys(v['summary']).every(
          key =>
            typeof key === 'string' &&
            Array.isArray(v['summary'][key]) &&
            v['summary'][key].every(
              elmt =>
                Array.isArray(elmt) &&
                elmt.length == 2 &&
                typeof elmt[0] === 'string' &&
                typeof elmt[1] === 'number'
            )
        ))) &&
    ((v['alertedContainers'] && isError(v['alertedContainers'])) ||
      (Array.isArray(v['alertedContainers']) &&
        v['alertedContainers'].every(elmt => typeof elmt === 'string')))
  );
}
