// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface CriteriaItem {
  name: string;
}

export function isCriteriaItem(v: any): v is CriteriaItem {
  return (
    ((typeof v['name']) === 'string')
  );
}
