// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { CustomChecks, isCustomChecks } from './CustomChecks';

export interface CustomCheckData {
  config: CustomChecks;
}

export function isCustomCheckData(v: any): v is CustomCheckData {
  return v['config'] && isCustomChecks(v['config']);
}
