// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { CustomCheckConfig, isCustomCheckConfig } from './CustomCheckConfig';

export interface CustomCheckConfigDTO {
  group: string;
  config: CustomCheckConfig;
}

export function isCustomCheckConfigDTO(v: any): v is CustomCheckConfigDTO {
  return (
    typeof v['group'] === 'string' &&
    v['config'] &&
    isCustomCheckConfig(v['config'])
  );
}
