// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class CustomCheckConfigJsonProtocol {
  private static instance: CustomCheckConfigJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!CustomCheckConfigJsonProtocol.instance) {
      CustomCheckConfigJsonProtocol.instance = new CustomCheckConfigJsonProtocol();
    }

    return CustomCheckConfigJsonProtocol.instance;
  }
}

export const CustomCheckConfigJsonProtocolInhabitant: CustomCheckConfigJsonProtocol = CustomCheckConfigJsonProtocol.getInstance();

export function isCustomCheckConfigJsonProtocol(v: any): v is CustomCheckConfigJsonProtocol {
  return (v instanceof CustomCheckConfigJsonProtocol) && (v === CustomCheckConfigJsonProtocolInhabitant);
}
