// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface CustomCheck {
  name: string;
  script: string;
}

export function isCustomCheck(v: any): v is CustomCheck {
  return typeof v['name'] === 'string' && typeof v['script'] === 'string';
}
