// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { CustomChecks, isCustomChecks } from './CustomChecks';

export interface CustomCheckConfig {
  add?: CustomChecks;
  delete?: CustomChecks;
  update?: CustomChecks;
}

export function isCustomCheckConfig(v: any): v is CustomCheckConfig {
  return (
    (!v['add'] || (v['add'] && isCustomChecks(v['add']))) &&
    (!v['delete'] || (v['delete'] && isCustomChecks(v['delete']))) &&
    (!v['update'] || (v['update'] && isCustomChecks(v['update'])))
  );
}
