// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { CustomCheckConfig, isCustomCheckConfig } from './CustomCheckConfig';

export interface CustomCheckConfigData {
  config: CustomCheckConfig;
}

export function isCustomCheckConfigData(v: any): v is CustomCheckConfigData {
  return v['config'] && isCustomCheckConfig(v['config']);
}
