// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface DashboardViolation {
  policy_id: number;
  host_name: string;
  level: string;
  client_id: string;
  client_ip?: string;
  client_name?: string;
  client_domain?: string;
  server_id: string;
  server_ip?: string;
  server_name?: string;
  server_domain?: string;
  server_port?: number;
  application?: string;
  reported_at: DateTime;
}

export function isDashboardViolation(v: any): v is DashboardViolation {
  return (
    typeof v['policy_id'] === 'number' &&
    typeof v['host_name'] === 'string' &&
    typeof v['level'] === 'string' &&
    typeof v['client_id'] === 'string' &&
    (!v['client_ip'] || typeof v['client_ip'] === 'string') &&
    (!v['client_name'] || typeof v['client_name'] === 'string') &&
    (!v['client_domain'] || typeof v['client_domain'] === 'string') &&
    typeof v['server_id'] === 'string' &&
    (!v['server_ip'] || typeof v['server_ip'] === 'string') &&
    (!v['server_name'] || typeof v['server_name'] === 'string') &&
    (!v['server_domain'] || typeof v['server_domain'] === 'string') &&
    (!v['server_port'] || typeof v['server_port'] === 'number') &&
    (!v['application'] || typeof v['application'] === 'string') &&
    v['reported_at'] &&
    isDateTime(v['reported_at'])
  );
}
