// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface DashboardThreatData {
  threats: Array;
  error?: Error;
}

export function isDashboardThreatData(v: any): v is DashboardThreatData {
  return (
    v['threats'] &&
    isArray(v['threats']) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
