// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface DashboardViolationData {
  violations: Array;
  error?: Error;
}

export function isDashboardViolationData(v: any): v is DashboardViolationData {
  return (
    (v['violations'] && isArray(v['violations'])) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
