// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface DashboardNotificationDTO2 {
  criticalSecurityEvents: Error | CriticalDashboardSecurityEventDTO;
}

export function isDashboardNotificationDTO2(
  v: any
): v is DashboardNotificationDTO2 {
  return (
    (v['criticalSecurityEvents'] && isError(v['criticalSecurityEvents'])) ||
    (v['criticalSecurityEvents'] &&
      isCriticalDashboardSecurityEventDTO(v['criticalSecurityEvents']))
  );
}
