// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class DashboardSecurityEventsProtocol {
  private static instance: DashboardSecurityEventsProtocol;

  private constructor() {}

  public static getInstance() {
    if (!DashboardSecurityEventsProtocol.instance) {
      DashboardSecurityEventsProtocol.instance = new DashboardSecurityEventsProtocol();
    }

    return DashboardSecurityEventsProtocol.instance;
  }
}

export const DashboardSecurityEventsProtocolInhabitant: DashboardSecurityEventsProtocol = DashboardSecurityEventsProtocol.getInstance();

export function isDashboardSecurityEventsProtocol(v: any): v is DashboardSecurityEventsProtocol {
  return (v instanceof DashboardSecurityEventsProtocol) && (v === DashboardSecurityEventsProtocolInhabitant);
}
