// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import {
  CriticalSecurityEventDTO,
  isCriticalSecurityEventDTO,
} from './CriticalSecurityEventDTO';
import { ScoreInput, isScoreInput } from './ScoreInput';
import { ScoreOutput, isScoreOutput } from './ScoreOutput';
import { VulnerabilitiesDTO, isVulnerabilitiesDTO } from './VulnerabilitiesDTO';

export interface DashboardDTO {
  highPriorityVulnerabilities: VulnerabilitiesDTO;
  criticalSecurityEvents: CriticalSecurityEventDTO;
  topIncidents: Error | TopIncidentsDTO;
  containers: Error | Array;
  services: Error | Array;
  applications: Error | ReadonlyArray<[string, number]>;
  applications2: Error | ReadonlyArray<[string, ApplicationAnalysis]>;
  policyCoverage: Error | PolicyCoverage;
  exposedConversations: Error | ExposedConversations;
  autoScanConfig: Error | boolean;
  scoreInput: ScoreInput;
  scoreOutput: ScoreOutput;
}

export function isDashboardDTO(v: any): v is DashboardDTO {
  return (
    v['highPriorityVulnerabilities'] &&
    isVulnerabilitiesDTO(v['highPriorityVulnerabilities']) &&
    v['criticalSecurityEvents'] &&
    isCriticalSecurityEventDTO(v['criticalSecurityEvents']) &&
    ((v['topIncidents'] && isError(v['topIncidents'])) ||
      (v['topIncidents'] && isTopIncidentsDTO(v['topIncidents']))) &&
    ((v['containers'] && isError(v['containers'])) ||
      (v['containers'] && isArray(v['containers']))) &&
    ((v['services'] && isError(v['services'])) ||
      (v['services'] && isArray(v['services']))) &&
    ((v['applications'] && isError(v['applications'])) ||
      (Array.isArray(v['applications']) &&
        v['applications'].every(
          elmt =>
            Array.isArray(elmt) &&
            elmt.length == 2 &&
            typeof elmt[0] === 'string' &&
            typeof elmt[1] === 'number'
        ))) &&
    ((v['applications2'] && isError(v['applications2'])) ||
      (Array.isArray(v['applications2']) &&
        v['applications2'].every(
          elmt =>
            Array.isArray(elmt) &&
            elmt.length == 2 &&
            typeof elmt[0] === 'string' &&
            elmt[1] &&
            isApplicationAnalysis(elmt[1])
        ))) &&
    ((v['policyCoverage'] && isError(v['policyCoverage'])) ||
      (v['policyCoverage'] && isPolicyCoverage(v['policyCoverage']))) &&
    ((v['exposedConversations'] && isError(v['exposedConversations'])) ||
      (v['exposedConversations'] &&
        isExposedConversations(v['exposedConversations']))) &&
    ((v['autoScanConfig'] && isError(v['autoScanConfig'])) ||
      typeof v['autoScanConfig'] === 'boolean') &&
    v['scoreInput'] &&
    isScoreInput(v['scoreInput']) &&
    v['scoreOutput'] &&
    isScoreOutput(v['scoreOutput'])
  );
}
