// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import {
  CriticalSecurityEventDTO,
  isCriticalSecurityEventDTO,
} from './CriticalSecurityEventDTO';

export interface DashboardNotificationDTO {
  criticalSecurityEvents: CriticalSecurityEventDTO;
  topIncidents: Error | TopIncidentsDTO;
}

export function isDashboardNotificationDTO(
  v: any
): v is DashboardNotificationDTO {
  return (
    v['criticalSecurityEvents'] &&
    isCriticalSecurityEventDTO(v['criticalSecurityEvents']) &&
    ((v['topIncidents'] && isError(v['topIncidents'])) ||
      (v['topIncidents'] && isTopIncidentsDTO(v['topIncidents'])))
  );
}
