// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface DeployFedRulesConfig {
  force: boolean;
  ids: Array;
}

export function isDeployFedRulesConfig(v: any): v is DeployFedRulesConfig {
  return (
    ((typeof v['force']) === 'boolean') &&
    (v['ids'] && isArray(v['ids']))
  );
}
