// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface DeployFedRulesReq {
  ids?: ReadonlyArray<string>;
}

export function isDeployFedRulesReq(v: any): v is DeployFedRulesReq {
  return (
    !v['ids'] ||
    (Array.isArray(v['ids']) &&
      v['ids'].every(elmt => typeof elmt === 'string'))
  );
}
