// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpGroup, isDlpGroup } from './DlpGroup';

export interface DlpGroupsData {
  dlp_groups: ReadonlyArray<DlpGroup>;
}

export function isDlpGroupsData(v: any): v is DlpGroupsData {
  return (
    Array.isArray(v['dlp_groups']) &&
    v['dlp_groups'].every(elmt => elmt && isDlpGroup(elmt))
  );
}
