// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpGroup, isDlpGroup } from './DlpGroup';

export interface DlpGroupData {
  dlp_group: DlpGroup;
}

export function isDlpGroupData(v: any): v is DlpGroupData {
  return (
    (v['dlp_group'] && isDlpGroup(v['dlp_group']))
  );
}
