// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class DlpJsonProtocol {
  private static instance: DlpJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!DlpJsonProtocol.instance) {
      DlpJsonProtocol.instance = new DlpJsonProtocol();
    }

    return DlpJsonProtocol.instance;
  }
}

export const DlpJsonProtocolInhabitant: DlpJsonProtocol =
  DlpJsonProtocol.getInstance();

export function isDlpJsonProtocol(v: any): v is DlpJsonProtocol {
  return v instanceof DlpJsonProtocol && v === DlpJsonProtocolInhabitant;
}
