// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpRule, isDlpRule } from './DlpRule';

export interface DlpRulesData {
  rules: ReadonlyArray<DlpRule>;
}

export function isDlpRulesData(v: any): v is DlpRulesData {
  return (
    (Array.isArray(v['rules']) && v['rules'].every(elmt => elmt && isDlpRule(elmt)))
  );
}
