// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpRuleConfig, isDlpRuleConfig } from './DlpRuleConfig';

export interface DlpRuleConfigData {
  config: DlpRuleConfig;
}

export function isDlpRuleConfigData(v: any): v is DlpRuleConfigData {
  return v['config'] && isDlpRuleConfig(v['config']);
}
