// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Pattern, isPattern } from './Pattern';

export interface DlpRule {
  name: string;
  id?: number;
  patterns: ReadonlyArray<Pattern>;
}

export function isDlpRule(v: any): v is DlpRule {
  return (
    ((typeof v['name']) === 'string') &&
    (!v['id'] || ((typeof v['id']) === 'number')) &&
    (Array.isArray(v['patterns']) && v['patterns'].every(elmt => elmt && isPattern(elmt)))
  );
}
