// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpRuleDetail, isDlpRuleDetail } from './DlpRuleDetail';

export interface DlpRuleData {
  rule: DlpRuleDetail;
}

export function isDlpRuleData(v: any): v is DlpRuleData {
  return v['rule'] && isDlpRuleDetail(v['rule']);
}
