// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpRule, isDlpRule } from './DlpRule';

export interface DlpRuleDetail {
  sensors: ReadonlyArray<string>;
  rules: ReadonlyArray<DlpRule>;
}

export function isDlpRuleDetail(v: any): v is DlpRuleDetail {
  return (
    Array.isArray(v['sensors']) &&
    v['sensors'].every(elmt => typeof elmt === 'string') &&
    Array.isArray(v['rules']) &&
    v['rules'].every(elmt => elmt && isDlpRule(elmt))
  );
}
