// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpSensorConfig, isDlpSensorConfig } from './DlpSensorConfig';

export interface DlpSensorConfigData {
  config: DlpSensorConfig;
}

export function isDlpSensorConfigData(v: any): v is DlpSensorConfigData {
  return (
    (v['config'] && isDlpSensorConfig(v['config']))
  );
}
