// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpSensor, isDlpSensor } from './DlpSensor';

export interface DlpSensorsData {
  sensors: ReadonlyArray<DlpSensor>;
}

export function isDlpSensorsData(v: any): v is DlpSensorsData {
  return (
    Array.isArray(v['sensors']) &&
    v['sensors'].every(elmt => elmt && isDlpSensor(elmt))
  );
}
