// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface DlpSetting {
  name: string;
  action: string;
}

export function isDlpSetting(v: any): v is DlpSetting {
  return typeof v['name'] === 'string' && typeof v['action'] === 'string';
}
