// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DlpSensor, isDlpSensor } from './DlpSensor';

export interface DlpSensorData {
  sensor: DlpSensor;
}

export function isDlpSensorData(v: any): v is DlpSensorData {
  return (
    (v['sensor'] && isDlpSensor(v['sensor']))
  );
}
