// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DomainConfig, isDomainConfig } from './DomainConfig';

export interface DomainConfigData {
  config: DomainConfig;
}

export function isDomainConfigData(v: any): v is DomainConfigData {
  return (
    (v['config'] && isDomainConfig(v['config']))
  );
}
