// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface DomainConfig {
  tag_per_domain?: boolean;
}

export function isDomainConfig(v: any): v is DomainConfig {
  return (
    (!v['tag_per_domain'] || ((typeof v['tag_per_domain']) === 'boolean'))
  );
}
