// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { EndpointConfig, isEndpointConfig } from './EndpointConfig';

export interface EndpointConfigWrap {
  config: EndpointConfig;
}

export function isEndpointConfigWrap(v: any): v is EndpointConfigWrap {
  return v['config'] && isEndpointConfig(v['config']);
}
