// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface EndpointConfig {
  id: string;
  display_name?: string;
}

export function isEndpointConfig(v: any): v is EndpointConfig {
  return (
    typeof v['id'] === 'string' &&
    (!v['display_name'] || typeof v['display_name'] === 'string')
  );
}
