// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class EndpointConfigJsonProtocol {
  private static instance: EndpointConfigJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!EndpointConfigJsonProtocol.instance) {
      EndpointConfigJsonProtocol.instance = new EndpointConfigJsonProtocol();
    }

    return EndpointConfigJsonProtocol.instance;
  }
}

export const EndpointConfigJsonProtocolInhabitant: EndpointConfigJsonProtocol = EndpointConfigJsonProtocol.getInstance();

export function isEndpointConfigJsonProtocol(v: any): v is EndpointConfigJsonProtocol {
  return (v instanceof EndpointConfigJsonProtocol) && (v === EndpointConfigJsonProtocolInhabitant);
}
