// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface EndpointConversationData {
  conversations: Array;
}

export function isEndpointConversationData(v: any): v is EndpointConversationData {
  return (
    (v['conversations'] && isArray(v['conversations']))
  );
}
