// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Error {
  message: string;
}

export function isError(v: any): v is Error {
  return typeof v['message'] === 'string';
}
