// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Eula, isEula } from './Eula';

export interface EulaWrap {
  eula: Eula;
}

export function isEulaWrap(v: any): v is EulaWrap {
  return v['eula'] && isEula(v['eula']);
}
