// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ExportedWafSensorList {
  names: Array;
}

export function isExportedWafSensorList(v: any): v is ExportedWafSensorList {
  return v['names'] && isArray(v['names']);
}
