// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface Exposure {
  id: string;
  name: string;
  display_name: string;
  pod_name: string;
  service: string;
  severity: string;
  policy_mode: string;
  policy_action: string;
  protocols?: Array;
  applications?: Array;
  ports?: Array;
}

export function isExposure(v: any): v is Exposure {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['display_name']) === 'string') &&
    ((typeof v['pod_name']) === 'string') &&
    ((typeof v['service']) === 'string') &&
    ((typeof v['severity']) === 'string') &&
    ((typeof v['policy_mode']) === 'string') &&
    ((typeof v['policy_action']) === 'string') &&
    (!v['protocols'] || (v['protocols'] && isArray(v['protocols']))) &&
    (!v['applications'] || (v['applications'] && isArray(v['applications']))) &&
    (!v['ports'] || (v['ports'] && isArray(v['ports'])))
  );
}
