// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ExposedConversations {
  ingress: Array;
  egress: Array;
}

export function isExposedConversations(v: any): v is ExposedConversations {
  return (
    (v['ingress'] && isArray(v['ingress'])) &&
    (v['egress'] && isArray(v['egress']))
  );
}
