// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ClusterServerInfo, isClusterServerInfo } from './ClusterServerInfo';

export interface FedConfigData {
  poll_interval: number;
  name?: string;
  use_proxy?: string;
  rest_info?: ClusterServerInfo;
}

export function isFedConfigData(v: any): v is FedConfigData {
  return (
    ((typeof v['poll_interval']) === 'number') &&
    (!v['name'] || ((typeof v['name']) === 'string')) &&
    (!v['use_proxy'] || ((typeof v['use_proxy']) === 'string')) &&
    (!v['rest_info'] || (v['rest_info'] && isClusterServerInfo(v['rest_info'])))
  );
}
