// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ClusterServerInfo, isClusterServerInfo } from './ClusterServerInfo';

export interface FedJointCluster {
  name: string;
  id: string;
  secret: string;
  client_key_path?: string;
  client_cert_path?: string;
  user?: string;
  status?: string;
  rest_info: ClusterServerInfo;
  proxy_required?: boolean;
}

export function isFedJointCluster(v: any): v is FedJointCluster {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['id']) === 'string') &&
    ((typeof v['secret']) === 'string') &&
    (!v['client_key_path'] || ((typeof v['client_key_path']) === 'string')) &&
    (!v['client_cert_path'] || ((typeof v['client_cert_path']) === 'string')) &&
    (!v['user'] || ((typeof v['user']) === 'string')) &&
    (!v['status'] || ((typeof v['status']) === 'string')) &&
    (v['rest_info'] && isClusterServerInfo(v['rest_info'])) &&
    (!v['proxy_required'] || ((typeof v['proxy_required']) === 'boolean'))
  );
}
