// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface FedLeaveRequest {
}

export function isFedLeaveRequest(v: any): v is FedLeaveRequest {
  return (
    v === {}
  );
}
