// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ClusterServerInfo, isClusterServerInfo } from './ClusterServerInfo';

export interface FedMasterCluster {
  name: string;
  id: string;
  secret: string;
  ca_cert_path?: string;
  user?: string;
  status?: string;
  rest_info: ClusterServerInfo;
}

export function isFedMasterCluster(v: any): v is FedMasterCluster {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['id']) === 'string') &&
    ((typeof v['secret']) === 'string') &&
    (!v['ca_cert_path'] || ((typeof v['ca_cert_path']) === 'string')) &&
    (!v['user'] || ((typeof v['user']) === 'string')) &&
    (!v['status'] || ((typeof v['status']) === 'string')) &&
    (v['rest_info'] && isClusterServerInfo(v['rest_info']))
  );
}
