// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface FedMembershipData {
  fed_role: string;
}

export function isFedMembershipData(v: any): v is FedMembershipData {
  return typeof v['fed_role'] === 'string';
}
