// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ClusterServerInfo, isClusterServerInfo } from './ClusterServerInfo';

export interface FedPromptRequest {
  name: string;
  master_rest_info?: ClusterServerInfo;
  use_proxy?: string;
}

export function isFedPromptRequest(v: any): v is FedPromptRequest {
  return (
    ((typeof v['name']) === 'string') &&
    (!v['master_rest_info'] || (v['master_rest_info'] && isClusterServerInfo(v['master_rest_info']))) &&
    (!v['use_proxy'] || ((typeof v['use_proxy']) === 'string'))
  );
}
