// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface FileMonitorFilter {
  filter: string;
  behavior: string;
}

export function isFileMonitorFilter(v: any): v is FileMonitorFilter {
  return (
    ((typeof v['filter']) === 'string') &&
    ((typeof v['behavior']) === 'string')
  );
}
