// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { FileMonitorConfigData, isFileMonitorConfigData } from './FileMonitorConfigData';

export interface FileMonitorConfigDTO {
  group: string;
  fileMonitorConfigData: FileMonitorConfigData;
}

export function isFileMonitorConfigDTO(v: any): v is FileMonitorConfigDTO {
  return (
    ((typeof v['group']) === 'string') &&
    (v['fileMonitorConfigData'] && isFileMonitorConfigData(v['fileMonitorConfigData']))
  );
}
