// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { FileMonitorConfig, isFileMonitorConfig } from './FileMonitorConfig';

export interface FileMonitorConfigData {
  config: FileMonitorConfig;
}

export function isFileMonitorConfigData(v: any): v is FileMonitorConfigData {
  return v['config'] && isFileMonitorConfig(v['config']);
}
