// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { FileMonitorProfile, isFileMonitorProfile } from './FileMonitorProfile';

export interface FileMonitorProfileData {
  profile: FileMonitorProfile;
}

export function isFileMonitorProfileData(v: any): v is FileMonitorProfileData {
  return v['profile'] && isFileMonitorProfile(v['profile']);
}
