// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface GcrKey {
  json_key?: string;
}

export function isGcrKey(v: any): v is GcrKey {
  return !v['json_key'] || typeof v['json_key'] === 'string';
}
