// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface GraphData {
  endpoints: Array;
  conversations: Array;
  error?: Error;
}

export function isGraphData(v: any): v is GraphData {
  return (
    (v['endpoints'] && isArray(v['endpoints'])) &&
    (v['conversations'] && isArray(v['conversations'])) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
