// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface Groups {
  groups: Array;
}

export function isGroups(v: any): v is Groups {
  return v['groups'] && isArray(v['groups']);
}
