// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { GroupDTO, isGroupDTO } from './GroupDTO';

export interface GroupDTOWrap {
  group: GroupDTO;
}

export function isGroupDTOWrap(v: any): v is GroupDTOWrap {
  return (
    (v['group'] && isGroupDTO(v['group']))
  );
}
