// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Group4SingleDTO, isGroup4SingleDTO } from './Group4SingleDTO';

export interface Group4SingleDTOWrap {
  group: Group4SingleDTO;
}

export function isGroup4SingleDTOWrap(v: any): v is Group4SingleDTOWrap {
  return v['group'] && isGroup4SingleDTO(v['group']);
}
