// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface GroupMappedRole {
  group: string;
  global_role: string;
  role_domains?: { [key: string]: Array };
}

export function isGroupMappedRole(v: any): v is GroupMappedRole {
  return (
    ((typeof v['group']) === 'string') &&
    ((typeof v['global_role']) === 'string') &&
    (!v['role_domains'] || ((typeof v['role_domains']) == 'object' && Object.keys(v['role_domains']).every(key => ((typeof key) === 'string') && (v['role_domains'][key] && isArray(v['role_domains'][key])))))
  );
}
