// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface Group {
  name: string;
  comment: string;
  domain: string;
  criteria: Array;
  members: Array;
  response_rules?: Array;
  policy_mode?: string;
  cap_change_mode?: boolean;
  cap_scorable?: boolean;
  kind: string;
  cfg_type?: string;
  not_scored: boolean;
}

export function isGroup(v: any): v is Group {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['comment']) === 'string') &&
    ((typeof v['domain']) === 'string') &&
    (v['criteria'] && isArray(v['criteria'])) &&
    (v['members'] && isArray(v['members'])) &&
    (!v['response_rules'] || (v['response_rules'] && isArray(v['response_rules']))) &&
    (!v['policy_mode'] || ((typeof v['policy_mode']) === 'string')) &&
    (!v['cap_change_mode'] || ((typeof v['cap_change_mode']) === 'boolean')) &&
    (!v['cap_scorable'] || ((typeof v['cap_scorable']) === 'boolean')) &&
    ((typeof v['kind']) === 'string') &&
    (!v['cfg_type'] || ((typeof v['cfg_type']) === 'string')) &&
    ((typeof v['not_scored']) === 'boolean')
  );
}
