// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Group4Single, isGroup4Single } from './Group4Single';

export interface Group4SingleWrap {
  group: Group4Single;
}

export function isGroup4SingleWrap(v: any): v is Group4SingleWrap {
  return v['group'] && isGroup4Single(v['group']);
}
