// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface GroupDTOs {
  groups: Array;
}

export function isGroupDTOs(v: any): v is GroupDTOs {
  return v['groups'] && isArray(v['groups']);
}
