// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface GroupConfigDTO {
  name: string;
  comment: string;
  criteria: Array;
  cfg_type?: string;
}

export function isGroupConfigDTO(v: any): v is GroupConfigDTO {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['comment']) === 'string') &&
    (v['criteria'] && isArray(v['criteria'])) &&
    (!v['cfg_type'] || ((typeof v['cfg_type']) === 'string'))
  );
}
