// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface IncidentDetailsData {
  incidents: Array;
}

export function isIncidentDetailsData(v: any): v is IncidentDetailsData {
  return (
    (v['incidents'] && isArray(v['incidents']))
  );
}
