// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface IncidentsEndpoint {
  incidents: Array;
  error?: Error;
}

export function isIncidentsEndpoint(v: any): v is IncidentsEndpoint {
  return (
    v['incidents'] &&
    isArray(v['incidents']) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
