// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface Incidents {
  name: string;
  proc_cmd?: string;
  proc_effective_user?: string;
  workload_name?: string;
  remote_workload_name?: string;
  host_name?: string;
  client_ip?: string;
  server_ip?: string;
  reported_at: DateTime;
  reported_timestamp: number;
}

export function isIncidents(v: any): v is Incidents {
  return (
    typeof v['name'] === 'string' &&
    (!v['proc_cmd'] || typeof v['proc_cmd'] === 'string') &&
    (!v['proc_effective_user'] ||
      typeof v['proc_effective_user'] === 'string') &&
    (!v['workload_name'] || typeof v['workload_name'] === 'string') &&
    (!v['remote_workload_name'] ||
      typeof v['remote_workload_name'] === 'string') &&
    (!v['host_name'] || typeof v['host_name'] === 'string') &&
    (!v['client_ip'] || typeof v['client_ip'] === 'string') &&
    (!v['server_ip'] || typeof v['server_ip'] === 'string') &&
    v['reported_at'] &&
    isDateTime(v['reported_at']) &&
    typeof v['reported_timestamp'] === 'number'
  );
}
