// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface IncidentMajorData {
  incidents: Array;
}

export function isIncidentMajorData(v: any): v is IncidentMajorData {
  return v['incidents'] && isArray(v['incidents']);
}
