// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface IngressEgressRisk {
  discoverMode: number;
  monitorMode: number;
  protectMode: number;
  threat: number;
  violation: number;
}

export function isIngressEgressRisk(v: any): v is IngressEgressRisk {
  return (
    ((typeof v['discoverMode']) === 'number') &&
    ((typeof v['monitorMode']) === 'number') &&
    ((typeof v['protectMode']) === 'number') &&
    ((typeof v['threat']) === 'number') &&
    ((typeof v['violation']) === 'number')
  );
}
