// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Metrics, isMetrics } from './Metrics';

export interface InternalSystemData {
  metrics: Metrics;
  ingress: Array;
  egress: Array;
  hasError?: boolean;
}

export function isInternalSystemData(v: any): v is InternalSystemData {
  return (
    v['metrics'] &&
    isMetrics(v['metrics']) &&
    v['ingress'] &&
    isArray(v['ingress']) &&
    v['egress'] &&
    isArray(v['egress']) &&
    (!v['hasError'] || typeof v['hasError'] === 'boolean')
  );
}
