// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface IpAddress {
  ip: string;
  ip_prefix: number;
  gateway: string;
}

export function isIpAddress(v: any): v is IpAddress {
  return (
    typeof v['ip'] === 'string' &&
    typeof v['ip_prefix'] === 'number' &&
    typeof v['gateway'] === 'string'
  );
}
