// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class IpGeoJsonProtocol {
  private static instance: IpGeoJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!IpGeoJsonProtocol.instance) {
      IpGeoJsonProtocol.instance = new IpGeoJsonProtocol();
    }

    return IpGeoJsonProtocol.instance;
  }
}

export const IpGeoJsonProtocolInhabitant: IpGeoJsonProtocol = IpGeoJsonProtocol.getInstance();

export function isIpGeoJsonProtocol(v: any): v is IpGeoJsonProtocol {
  return (v instanceof IpGeoJsonProtocol) && (v === IpGeoJsonProtocolInhabitant);
}
