// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class IpGeoManager {
  private static instance: IpGeoManager;

  private constructor() {}

  public static getInstance() {
    if (!IpGeoManager.instance) {
      IpGeoManager.instance = new IpGeoManager();
    }

    return IpGeoManager.instance;
  }
}

export const IpGeoManagerInhabitant: IpGeoManager = IpGeoManager.getInstance();

export function isIpGeoManager(v: any): v is IpGeoManager {
  return v instanceof IpGeoManager && v === IpGeoManagerInhabitant;
}
