// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface IpGeo {
  from: number;
  to: number;
  country_code: string;
  country_name: string;
}

export function isIpGeo(v: any): v is IpGeo {
  return (
    ((typeof v['from']) === 'number') &&
    ((typeof v['to']) === 'number') &&
    ((typeof v['country_code']) === 'string') &&
    ((typeof v['country_name']) === 'string')
  );
}
