// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface JfrogXray {
  url: string;
  enable: boolean;
  username: string;
  password?: string;
}

export function isJfrogXray(v: any): v is JfrogXray {
  return (
    typeof v['url'] === 'string' &&
    typeof v['enable'] === 'boolean' &&
    typeof v['username'] === 'string' &&
    (!v['password'] || typeof v['password'] === 'string')
  );
}
