// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface LdapTestAccount {
  username: string;
  password: string;
}

export function isLdapTestAccount(v: any): v is LdapTestAccount {
  return typeof v['username'] === 'string' && typeof v['password'] === 'string';
}
