// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { LdapSetting, isLdapSetting } from './LdapSetting';

export interface LdapSettingWrap {
  config: LdapSetting;
}

export function isLdapSettingWrap(v: any): v is LdapSettingWrap {
  return (
    (v['config'] && isLdapSetting(v['config']))
  );
}
