// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface LicenseRequest {
  name: string;
  email: string;
  months: number;
  node_limit: number;
  multi_cluster_limit?: number;
  scan: boolean;
  enforce?: boolean;
}

export function isLicenseRequest(v: any): v is LicenseRequest {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['email']) === 'string') &&
    ((typeof v['months']) === 'number') &&
    ((typeof v['node_limit']) === 'number') &&
    (!v['multi_cluster_limit'] || ((typeof v['multi_cluster_limit']) === 'number')) &&
    ((typeof v['scan']) === 'boolean') &&
    (!v['enforce'] || ((typeof v['enforce']) === 'boolean'))
  );
}
