// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface LicenseKey {
  license_key: string;
}

export function isLicenseKey(v: any): v is LicenseKey {
  return typeof v['license_key'] === 'string';
}
