// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { LicenseRequest, isLicenseRequest } from './LicenseRequest';

export interface LicenseRequestWrap {
  license_request: LicenseRequest;
}

export function isLicenseRequestWrap(v: any): v is LicenseRequestWrap {
  return (
    (v['license_request'] && isLicenseRequest(v['license_request']))
  );
}
