// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface LicenseCode {
  license_code: string;
}

export function isLicenseCode(v: any): v is LicenseCode {
  return typeof v['license_code'] === 'string';
}
