// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface MaskedAWSAccount {
  id: string;
  region: string;
}

export function isMaskedAWSAccount(v: any): v is MaskedAWSAccount {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['region']) === 'string')
  );
}
