// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface MaskedRegistryConfig {
  name: string;
  registry_type: string;
  filters?: Array;
  auth_with_token: boolean;
}

export function isMaskedRegistryConfig(v: any): v is MaskedRegistryConfig {
  return (
    typeof v['name'] === 'string' &&
    typeof v['registry_type'] === 'string' &&
    (!v['filters'] || (v['filters'] && isArray(v['filters']))) &&
    typeof v['auth_with_token'] === 'boolean'
  );
}
