// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class Md5 {
  public MD5: string = 'MD5';

  private static instance: Md5;

  private constructor() {}

  public static getInstance() {
    if (!Md5.instance) {
      Md5.instance = new Md5();
    }

    return Md5.instance;
  }
}

export const Md5Inhabitant: Md5 = Md5.getInstance();

export function isMd5(v: any): v is Md5 {
  return v instanceof Md5 && v === Md5Inhabitant;
}
