// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Score, isScore } from './Score';

export interface MultiClusterSummary {
  score: Score;
  summaryJson: string;
}

export function isMultiClusterSummary(v: any): v is MultiClusterSummary {
  return (
    v['score'] && isScore(v['score']) && typeof v['summaryJson'] === 'string'
  );
}
