// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface NamespaceEntryConfig {
  name: string;
  tags?: Array;
}

export function isNamespaceEntryConfig(v: any): v is NamespaceEntryConfig {
  return (
    ((typeof v['name']) === 'string') &&
    (!v['tags'] || (v['tags'] && isArray(v['tags'])))
  );
}
