// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { NamespaceConfig, isNamespaceConfig } from './NamespaceConfig';

export interface NamespaceConfigData {
  config: NamespaceConfig;
}

export function isNamespaceConfigData(v: any): v is NamespaceConfigData {
  return v['config'] && isNamespaceConfig(v['config']);
}
