// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { NamespaceConfig, isNamespaceConfig } from './NamespaceConfig';

export interface NamespaceEntryConfigData {
  config: NamespaceConfig;
}

export function isNamespaceEntryConfigData(v: any): v is NamespaceEntryConfigData {
  return (
    (v['config'] && isNamespaceConfig(v['config']))
  );
}
