// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface NamespacesData {
  domains: Array;
  tag_per_domain?: boolean;
}

export function isNamespacesData(v: any): v is NamespacesData {
  return (
    v['domains'] &&
    isArray(v['domains']) &&
    (!v['tag_per_domain'] || typeof v['tag_per_domain'] === 'boolean')
  );
}
