// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class NamespaceJsonProtocol {
  private static instance: NamespaceJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!NamespaceJsonProtocol.instance) {
      NamespaceJsonProtocol.instance = new NamespaceJsonProtocol();
    }

    return NamespaceJsonProtocol.instance;
  }
}

export const NamespaceJsonProtocolInhabitant: NamespaceJsonProtocol =
  NamespaceJsonProtocol.getInstance();

export function isNamespaceJsonProtocol(v: any): v is NamespaceJsonProtocol {
  return (
    v instanceof NamespaceJsonProtocol && v === NamespaceJsonProtocolInhabitant
  );
}
