// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ScanSummary4Dashboard, isScanSummary4Dashboard } from './ScanSummary4Dashboard';

export interface Nodes {
  id: string;
  name: string;
  os: string;
  scan_summary?: ScanSummary4Dashboard;
}

export function isNodes(v: any): v is Nodes {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['os']) === 'string') &&
    (!v['scan_summary'] || (v['scan_summary'] && isScanSummary4Dashboard(v['scan_summary'])))
  );
}
