// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { OpenIdServer, isOpenIdServer } from './OpenIdServer';

export interface OpenIdServerConfig {
  name: string;
  oidc: OpenIdServer;
}

export function isOpenIdServerConfig(v: any): v is OpenIdServerConfig {
  return (
    ((typeof v['name']) === 'string') &&
    (v['oidc'] && isOpenIdServer(v['oidc']))
  );
}
