// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface OpIndex {
  op: string;
  sign: string;
  index: number;
}

export function isOpIndex(v: any): v is OpIndex {
  return (
    typeof v['op'] === 'string' &&
    typeof v['sign'] === 'string' &&
    typeof v['index'] === 'number'
  );
}
