// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Password {
  username: string;
  password: string;
}

export function isPassword(v: any): v is Password {
  return typeof v['username'] === 'string' && typeof v['password'] === 'string';
}
