// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Permission {
  id: string;
  read: boolean;
  write: boolean;
}

export function isPermission(v: any): v is Permission {
  return (
    typeof v['id'] === 'string' &&
    typeof v['read'] === 'boolean' &&
    typeof v['write'] === 'boolean'
  );
}
