// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Platform {
  platform: string;
  high: number;
  medium: number;
  scanned_timestamp: number;
  scanned_at: string;
}

export function isPlatform(v: any): v is Platform {
  return (
    typeof v['platform'] === 'string' &&
    typeof v['high'] === 'number' &&
    typeof v['medium'] === 'number' &&
    typeof v['scanned_timestamp'] === 'number' &&
    typeof v['scanned_at'] === 'string'
  );
}
