// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Pod {
  id: string;
  name: string;
  display_name: string;
  domain: string;
  policy_mode?: string;
  image: string;
  state: string;
}

export function isPod(v: any): v is Pod {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['display_name']) === 'string') &&
    ((typeof v['domain']) === 'string') &&
    (!v['policy_mode'] || ((typeof v['policy_mode']) === 'string')) &&
    ((typeof v['image']) === 'string') &&
    ((typeof v['state']) === 'string')
  );
}
