// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class PolicyJsonProtocol {
  private static instance: PolicyJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!PolicyJsonProtocol.instance) {
      PolicyJsonProtocol.instance = new PolicyJsonProtocol();
    }

    return PolicyJsonProtocol.instance;
  }
}

export const PolicyJsonProtocolInhabitant: PolicyJsonProtocol =
  PolicyJsonProtocol.getInstance();

export function isPolicyJsonProtocol(v: any): v is PolicyJsonProtocol {
  return v instanceof PolicyJsonProtocol && v === PolicyJsonProtocolInhabitant;
}
