// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface Policy2 {
  rules?: Array;
  delete?: Array;
}

export function isPolicy2(v: any): v is Policy2 {
  return (
    (!v['rules'] || (v['rules'] && isArray(v['rules']))) &&
    (!v['delete'] || (v['delete'] && isArray(v['delete'])))
  );
}
