// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { RuleInsert, isRuleInsert } from './RuleInsert';

export interface PolicyRuleInsert {
  insert: RuleInsert;
}

export function isPolicyRuleInsert(v: any): v is PolicyRuleInsert {
  return (
    (v['insert'] && isRuleInsert(v['insert']))
  );
}
