// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface PreRuleContext {
  name: string;
  context: string;
}

export function isPreRuleContext(v: any): v is PreRuleContext {
  return typeof v['name'] === 'string' && typeof v['context'] === 'string';
}
