// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ProcessProfileConfig, isProcessProfileConfig } from './ProcessProfileConfig';

export interface ProcessProfileConfigData {
  process_profile_config: ProcessProfileConfig;
}

export function isProcessProfileConfigData(v: any): v is ProcessProfileConfigData {
  return (
    (v['process_profile_config'] && isProcessProfileConfig(v['process_profile_config']))
  );
}
