// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class ProcessProfileJsonProtocol {
  private static instance: ProcessProfileJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!ProcessProfileJsonProtocol.instance) {
      ProcessProfileJsonProtocol.instance = new ProcessProfileJsonProtocol();
    }

    return ProcessProfileJsonProtocol.instance;
  }
}

export const ProcessProfileJsonProtocolInhabitant: ProcessProfileJsonProtocol =
  ProcessProfileJsonProtocol.getInstance();

export function isProcessProfileJsonProtocol(
  v: any
): v is ProcessProfileJsonProtocol {
  return (
    v instanceof ProcessProfileJsonProtocol &&
    v === ProcessProfileJsonProtocolInhabitant
  );
}
