// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ProcessProfileConfig {
  group: string;
  process_delete_list?: Array;
  process_change_list?: Array;
  process_replace_list?: Array;
}

export function isProcessProfileConfig(v: any): v is ProcessProfileConfig {
  return (
    ((typeof v['group']) === 'string') &&
    (!v['process_delete_list'] || (v['process_delete_list'] && isArray(v['process_delete_list']))) &&
    (!v['process_change_list'] || (v['process_change_list'] && isArray(v['process_change_list']))) &&
    (!v['process_replace_list'] || (v['process_replace_list'] && isArray(v['process_replace_list'])))
  );
}
