// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ProcessProfileEntry {
  name: string;
  path?: string;
  user?: string;
  uid?: number;
  action: string;
}

export function isProcessProfileEntry(v: any): v is ProcessProfileEntry {
  return (
    ((typeof v['name']) === 'string') &&
    (!v['path'] || ((typeof v['path']) === 'string')) &&
    (!v['user'] || ((typeof v['user']) === 'string')) &&
    (!v['uid'] || ((typeof v['uid']) === 'number')) &&
    ((typeof v['action']) === 'string')
  );
}
