// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { RuleIds, isRuleIds } from './RuleIds';

export interface PromoteConfig {
  request: RuleIds;
}

export function isPromoteConfig(v: any): v is PromoteConfig {
  return v['request'] && isRuleIds(v['request']);
}
