// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { QuarantineConfig, isQuarantineConfig } from './QuarantineConfig';

export interface QuarantineConfigWarp {
  config: QuarantineConfig;
}

export function isQuarantineConfigWarp(v: any): v is QuarantineConfigWarp {
  return v['config'] && isQuarantineConfig(v['config']);
}
