// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface QuarantineConfig {
  quarantine: boolean;
}

export function isQuarantineConfig(v: any): v is QuarantineConfig {
  return (
    ((typeof v['quarantine']) === 'boolean')
  );
}
