// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface RedirectURL {
  redirect_endpoint: string;
}

export function isRedirectURL(v: any): v is RedirectURL {
  return (
    ((typeof v['redirect_endpoint']) === 'string')
  );
}
