// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { RegistryConfigWrap, isRegistryConfigWrap } from './RegistryConfigWrap';

export interface RegistryConfigDTO {
  wrap: RegistryConfigWrap;
  name: string;
}

export function isRegistryConfigDTO(v: any): v is RegistryConfigDTO {
  return (
    (v['wrap'] && isRegistryConfigWrap(v['wrap'])) &&
    ((typeof v['name']) === 'string')
  );
}
