// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface RegistryHttpProxy {
  url: string;
  username: string;
  password?: string;
}

export function isRegistryHttpProxy(v: any): v is RegistryHttpProxy {
  return (
    typeof v['url'] === 'string' &&
    typeof v['username'] === 'string' &&
    (!v['password'] || typeof v['password'] === 'string')
  );
}
