// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class RegistryConfigJsonProtocol {
  private static instance: RegistryConfigJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!RegistryConfigJsonProtocol.instance) {
      RegistryConfigJsonProtocol.instance = new RegistryConfigJsonProtocol();
    }

    return RegistryConfigJsonProtocol.instance;
  }
}

export const RegistryConfigJsonProtocolInhabitant: RegistryConfigJsonProtocol =
  RegistryConfigJsonProtocol.getInstance();

export function isRegistryConfigJsonProtocol(
  v: any
): v is RegistryConfigJsonProtocol {
  return (
    v instanceof RegistryConfigJsonProtocol &&
    v === RegistryConfigJsonProtocolInhabitant
  );
}
