// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface RegistryConfig {
  name: string;
  registry_type: string;
  filters?: Array;
  auth_with_token: boolean;
  auth_token?: string;
}

export function isRegistryConfig(v: any): v is RegistryConfig {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['registry_type']) === 'string') &&
    (!v['filters'] || (v['filters'] && isArray(v['filters']))) &&
    ((typeof v['auth_with_token']) === 'boolean') &&
    (!v['auth_token'] || ((typeof v['auth_token']) === 'string'))
  );
}
