// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface RegistyHttpProxy {
  url: string;
  username: string;
  password?: string;
}

export function isRegistyHttpProxy(v: any): v is RegistyHttpProxy {
  return (
    ((typeof v['url']) === 'string') &&
    ((typeof v['username']) === 'string') &&
    (!v['password'] || ((typeof v['password']) === 'string'))
  );
}
