// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { RegistryConfig, isRegistryConfig } from './RegistryConfig';

export interface RegistryConfigWrap {
  config: RegistryConfig;
}

export function isRegistryConfigWrap(v: any): v is RegistryConfigWrap {
  return v['config'] && isRegistryConfig(v['config']);
}
