// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface RegistryHttpsProxy {
  url: string;
  username: string;
  password?: string;
}

export function isRegistryHttpsProxy(v: any): v is RegistryHttpsProxy {
  return (
    typeof v['url'] === 'string' &&
    typeof v['username'] === 'string' &&
    (!v['password'] || typeof v['password'] === 'string')
  );
}
