// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Unquarantine, isUnquarantine } from './Unquarantine';

export interface Request {
  request: Unquarantine;
}

export function isRequest(v: any): v is Request {
  return v['request'] && isUnquarantine(v['request']);
}
