// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class ResourceJsonProtocol {
  public nginxTunnelSecured: string = "secured";

  public nginxTunnelPartial: string = "partial";

  public address: string = "address";

  private static instance: ResourceJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!ResourceJsonProtocol.instance) {
      ResourceJsonProtocol.instance = new ResourceJsonProtocol();
    }

    return ResourceJsonProtocol.instance;
  }
}

export const ResourceJsonProtocolInhabitant: ResourceJsonProtocol = ResourceJsonProtocol.getInstance();

export function isResourceJsonProtocol(v: any): v is ResourceJsonProtocol {
  return (v instanceof ResourceJsonProtocol) && (v === ResourceJsonProtocolInhabitant);
}
