// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ResponseRule, isResponseRule } from './ResponseRule';

export interface ResponseRuleConfig {
  config: ResponseRule;
}

export function isResponseRuleConfig(v: any): v is ResponseRuleConfig {
  return v['config'] && isResponseRule(v['config']);
}
