// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ResponseRules, isResponseRules } from './ResponseRules';

export interface ResponseRulesWrap {
  insert: ResponseRules;
}

export function isResponseRulesWrap(v: any): v is ResponseRulesWrap {
  return (
    (v['insert'] && isResponseRules(v['insert']))
  );
}
