// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ResponseRuleID {
  response_rule: number;
}

export function isResponseRuleID(v: any): v is ResponseRuleID {
  return (
    ((typeof v['response_rule']) === 'number')
  );
}
