// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface Role {
  name: string;
  comment?: string;
  permissions: Array;
}

export function isRole(v: any): v is Role {
  return (
    typeof v['name'] === 'string' &&
    (!v['comment'] || typeof v['comment'] === 'string') &&
    v['permissions'] &&
    isArray(v['permissions'])
  );
}
