// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface RuleInsert {
  rules: Array;
}

export function isRuleInsert(v: any): v is RuleInsert {
  return (
    (v['rules'] && isArray(v['rules']))
  );
}
