// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface Rule2 {
  id?: number;
  comment?: string;
  from?: string;
  to?: string;
  applications?: Array;
  ports?: string;
  action?: string;
  learned?: boolean;
  cfg_type?: string;
  disable?: boolean;
}

export function isRule2(v: any): v is Rule2 {
  return (
    (!v['id'] || typeof v['id'] === 'number') &&
    (!v['comment'] || typeof v['comment'] === 'string') &&
    (!v['from'] || typeof v['from'] === 'string') &&
    (!v['to'] || typeof v['to'] === 'string') &&
    (!v['applications'] || (v['applications'] && isArray(v['applications']))) &&
    (!v['ports'] || typeof v['ports'] === 'string') &&
    (!v['action'] || typeof v['action'] === 'string') &&
    (!v['learned'] || typeof v['learned'] === 'boolean') &&
    (!v['cfg_type'] || typeof v['cfg_type'] === 'string') &&
    (!v['disable'] || typeof v['disable'] === 'boolean')
  );
}
