// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { RuleConfig, isRuleConfig } from './RuleConfig';

export interface RuleConfigData {
  config: RuleConfig;
  replicate?: boolean;
}

export function isRuleConfigData(v: any): v is RuleConfigData {
  return (
    v['config'] &&
    isRuleConfig(v['config']) &&
    (!v['replicate'] || typeof v['replicate'] === 'boolean')
  );
}
