// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface RuleIds {
  ids: Array;
}

export function isRuleIds(v: any): v is RuleIds {
  return (
    (v['ids'] && isArray(v['ids']))
  );
}
