// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface RuleConfig {
  id: number;
  comment?: string;
  from?: string;
  to?: string;
  applications?: Array;
  ports?: string;
  action?: string;
  disable?: boolean;
}

export function isRuleConfig(v: any): v is RuleConfig {
  return (
    typeof v['id'] === 'number' &&
    (!v['comment'] || typeof v['comment'] === 'string') &&
    (!v['from'] || typeof v['from'] === 'string') &&
    (!v['to'] || typeof v['to'] === 'string') &&
    (!v['applications'] || (v['applications'] && isArray(v['applications']))) &&
    (!v['ports'] || typeof v['ports'] === 'string') &&
    (!v['action'] || typeof v['action'] === 'string') &&
    (!v['disable'] || typeof v['disable'] === 'boolean')
  );
}
