// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { SamlConfig, isSamlConfig } from './SamlConfig';

export interface SamlConfigWrap {
  config: SamlConfig;
}

export function isSamlConfigWrap(v: any): v is SamlConfigWrap {
  return v['config'] && isSamlConfig(v['config']);
}
