// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { SamlServer, isSamlServer } from './SamlServer';

export interface SamlConfig {
  name: string;
  saml: SamlServer;
}

export function isSamlConfig(v: any): v is SamlConfig {
  return typeof v['name'] === 'string' && v['saml'] && isSamlServer(v['saml']);
}
