// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface SamlResponse {
  client_ip: string;
}

export function isSamlResponse(v: any): v is SamlResponse {
  return (
    ((typeof v['client_ip']) === 'string')
  );
}
