// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface SamlServer {
  sso_url: string;
  issuer: string;
  x509_cert?: string;
  group_claim?: string;
  enable?: boolean;
  default_role?: string;
  group_mapped_roles?: Array;
}

export function isSamlServer(v: any): v is SamlServer {
  return (
    typeof v['sso_url'] === 'string' &&
    typeof v['issuer'] === 'string' &&
    (!v['x509_cert'] || typeof v['x509_cert'] === 'string') &&
    (!v['group_claim'] || typeof v['group_claim'] === 'string') &&
    (!v['enable'] || typeof v['enable'] === 'boolean') &&
    (!v['default_role'] || typeof v['default_role'] === 'string') &&
    (!v['group_mapped_roles'] ||
      (v['group_mapped_roles'] && isArray(v['group_mapped_roles'])))
  );
}
