// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ScanConfig, isScanConfig } from './ScanConfig';

export interface ScanConfigWrap {
  config: ScanConfig;
}

export function isScanConfigWrap(v: any): v is ScanConfigWrap {
  return v['config'] && isScanConfig(v['config']);
}
