// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ScanConfig {
  auto_scan: boolean;
}

export function isScanConfig(v: any): v is ScanConfig {
  return typeof v['auto_scan'] === 'boolean';
}
