// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ScanSummary4Dashboard {
  status: string;
  high: number;
  medium: number;
}

export function isScanSummary4Dashboard(v: any): v is ScanSummary4Dashboard {
  return (
    ((typeof v['status']) === 'string') &&
    ((typeof v['high']) === 'number') &&
    ((typeof v['medium']) === 'number')
  );
}
