// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ScanSummary {
  status: string;
  high: number;
  medium: number;
  hidden_high?: number;
  hidden_medium?: number;
  result: string;
  scanned_timestamp: number;
  scanned_at: string;
  base_os: string;
  scanner_version: string;
  cvedb_create_time: string;
}

export function isScanSummary(v: any): v is ScanSummary {
  return (
    typeof v['status'] === 'string' &&
    typeof v['high'] === 'number' &&
    typeof v['medium'] === 'number' &&
    (!v['hidden_high'] || typeof v['hidden_high'] === 'number') &&
    (!v['hidden_medium'] || typeof v['hidden_medium'] === 'number') &&
    typeof v['result'] === 'string' &&
    typeof v['scanned_timestamp'] === 'number' &&
    typeof v['scanned_at'] === 'string' &&
    typeof v['base_os'] === 'string' &&
    typeof v['scanner_version'] === 'string' &&
    typeof v['cvedb_create_time'] === 'string'
  );
}
