// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ScannedWorkloadsWrap2 {
  workloads: Array;
}

export function isScannedWorkloadsWrap2(v: any): v is ScannedWorkloadsWrap2 {
  return v['workloads'] && isArray(v['workloads']);
}
