// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ScanSchedule {
  schedule: string;
  interval: number;
}

export function isScanSchedule(v: any): v is ScanSchedule {
  return (
    ((typeof v['schedule']) === 'string') &&
    ((typeof v['interval']) === 'number')
  );
}
