// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ScoreOutput {
  new_service_mode_score: Error | number;
  service_mode_score: Error | number;
  service_mode_score_by_100: Error | number;
  exposure_score: Error | number;
  exposure_score_by_100: Error | number;
  privileged_container_score: Error | number;
  run_as_root_score: Error | number;
  admission_rule_score: Error | number;
  vulnerabilityScore: Error | number;
  vulnerability_score_by_100: Error | number;
  security_risk_score: Error | number;
}

export function isScoreOutput(v: any): v is ScoreOutput {
  return (
    ((v['new_service_mode_score'] && isError(v['new_service_mode_score'])) ||
      typeof v['new_service_mode_score'] === 'number') &&
    ((v['service_mode_score'] && isError(v['service_mode_score'])) ||
      typeof v['service_mode_score'] === 'number') &&
    ((v['service_mode_score_by_100'] &&
      isError(v['service_mode_score_by_100'])) ||
      typeof v['service_mode_score_by_100'] === 'number') &&
    ((v['exposure_score'] && isError(v['exposure_score'])) ||
      typeof v['exposure_score'] === 'number') &&
    ((v['exposure_score_by_100'] && isError(v['exposure_score_by_100'])) ||
      typeof v['exposure_score_by_100'] === 'number') &&
    ((v['privileged_container_score'] &&
      isError(v['privileged_container_score'])) ||
      typeof v['privileged_container_score'] === 'number') &&
    ((v['run_as_root_score'] && isError(v['run_as_root_score'])) ||
      typeof v['run_as_root_score'] === 'number') &&
    ((v['admission_rule_score'] && isError(v['admission_rule_score'])) ||
      typeof v['admission_rule_score'] === 'number') &&
    ((v['vulnerabilityScore'] && isError(v['vulnerabilityScore'])) ||
      typeof v['vulnerabilityScore'] === 'number') &&
    ((v['vulnerability_score_by_100'] &&
      isError(v['vulnerability_score_by_100'])) ||
      typeof v['vulnerability_score_by_100'] === 'number') &&
    ((v['security_risk_score'] && isError(v['security_risk_score'])) ||
      typeof v['security_risk_score'] === 'number')
  );
}
