// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Score {
  new_service_mode_score: number;
  service_mode_score: number;
  service_mode_score_by_100: number;
  exposure_score: number;
  exposure_score_by_100: number;
  privileged_container_score: number;
  run_as_root_score: number;
  admission_rule_score: number;
  vulnerabilityScore: number;
  vulnerability_score_by_100: number;
  security_risk_score: number;
  hasError: boolean;
}

export function isScore(v: any): v is Score {
  return (
    typeof v['new_service_mode_score'] === 'number' &&
    typeof v['service_mode_score'] === 'number' &&
    typeof v['service_mode_score_by_100'] === 'number' &&
    typeof v['exposure_score'] === 'number' &&
    typeof v['exposure_score_by_100'] === 'number' &&
    typeof v['privileged_container_score'] === 'number' &&
    typeof v['run_as_root_score'] === 'number' &&
    typeof v['admission_rule_score'] === 'number' &&
    typeof v['vulnerabilityScore'] === 'number' &&
    typeof v['vulnerability_score_by_100'] === 'number' &&
    typeof v['security_risk_score'] === 'number' &&
    typeof v['hasError'] === 'boolean'
  );
}
