// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { DateTime, isDateTime } from './DateTime';
import { Endpoint, isEndpoint } from './Endpoint';

export interface SecurityEvent {
  name: string;
  security_event_type: string;
  level: string;
  source: Endpoint;
  destination: Endpoint;
  host_name?: string;
  applications: Array;
  details: string;
  reported_timestamp: number;
  reported_at: DateTime;
}

export function isSecurityEvent(v: any): v is SecurityEvent {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['security_event_type']) === 'string') &&
    ((typeof v['level']) === 'string') &&
    (v['source'] && isEndpoint(v['source'])) &&
    (v['destination'] && isEndpoint(v['destination'])) &&
    (!v['host_name'] || ((typeof v['host_name']) === 'string')) &&
    (v['applications'] && isArray(v['applications'])) &&
    ((typeof v['details']) === 'string') &&
    ((typeof v['reported_timestamp']) === 'number') &&
    (v['reported_at'] && isDateTime(v['reported_at']))
  );
}
