// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface SecurityEventDTO {
  securityEvents: Array;
}

export function isSecurityEventDTO(v: any): v is SecurityEventDTO {
  return (
    (v['securityEvents'] && isArray(v['securityEvents']))
  );
}
