// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { User, isUser } from './User';

export interface SelfWrap {
  password_days_until_expire?: number;
  user: User;
}

export function isSelfWrap(v: any): v is SelfWrap {
  return (
    (!v['password_days_until_expire'] || ((typeof v['password_days_until_expire']) === 'number')) &&
    (v['user'] && isUser(v['user']))
  );
}
