// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ServiceConfigParam {
  policy_mode?: string;
  services?: Array;
  not_scored?: boolean;
}

export function isServiceConfigParam(v: any): v is ServiceConfigParam {
  return (
    (!v['policy_mode'] || ((typeof v['policy_mode']) === 'string')) &&
    (!v['services'] || (v['services'] && isArray(v['services']))) &&
    (!v['not_scored'] || ((typeof v['not_scored']) === 'boolean'))
  );
}
