// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ServiceConnectionRisk {
  discover: number;
  monitor: number;
  protect: number;
}

export function isServiceConnectionRisk(v: any): v is ServiceConnectionRisk {
  return (
    ((typeof v['discover']) === 'number') &&
    ((typeof v['monitor']) === 'number') &&
    ((typeof v['protect']) === 'number')
  );
}
