// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ServiceAddress {
  ip: string;
  port: number;
}

export function isServiceAddress(v: any): v is ServiceAddress {
  return typeof v['ip'] === 'string' && typeof v['port'] === 'number';
}
