// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ServiceConfigParam, isServiceConfigParam } from './ServiceConfigParam';

export interface ServiceConfig {
  config: ServiceConfigParam;
}

export function isServiceConfig(v: any): v is ServiceConfig {
  return (
    (v['config'] && isServiceConfigParam(v['config']))
  );
}
