// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface ServiceStatesIn {
  groups: Array;
  error?: Error;
}

export function isServiceStatesIn(v: any): v is ServiceStatesIn {
  return (
    v['groups'] &&
    isArray(v['groups']) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
