// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ServiceStateIn {
  domain: string;
  name: string;
  policy_mode?: string;
  platform_role: string;
  members: Array;
  not_scored: boolean;
  kind: string;
}

export function isServiceStateIn(v: any): v is ServiceStateIn {
  return (
    ((typeof v['domain']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    (!v['policy_mode'] || ((typeof v['policy_mode']) === 'string')) &&
    ((typeof v['platform_role']) === 'string') &&
    (v['members'] && isArray(v['members'])) &&
    ((typeof v['not_scored']) === 'boolean') &&
    ((typeof v['kind']) === 'string')
  );
}
