// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface SnifferParam {
  file_number?: number;
  duration?: number;
  filter?: string;
}

export function isSnifferParam(v: any): v is SnifferParam {
  return (
    (!v['file_number'] || typeof v['file_number'] === 'number') &&
    (!v['duration'] || typeof v['duration'] === 'number') &&
    (!v['filter'] || typeof v['filter'] === 'string')
  );
}
