// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { SnifferParamWarp, isSnifferParamWarp } from './SnifferParamWarp';

export interface SnifferData {
  workloadId: string;
  snifferParamWarp: SnifferParamWarp;
}

export function isSnifferData(v: any): v is SnifferData {
  return (
    typeof v['workloadId'] === 'string' &&
    v['snifferParamWarp'] &&
    isSnifferParamWarp(v['snifferParamWarp'])
  );
}
