// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface StatusCode {
  intValue: number;
  reason: string;
  defaultMessage: string;
  isSuccess: boolean;
  isFailure: boolean;
  allowsEntity: boolean;
}

export function isStatusCode(v: any): v is StatusCode {
  return (
    ((typeof v['intValue']) === 'number') &&
    ((typeof v['reason']) === 'string') &&
    ((typeof v['defaultMessage']) === 'string') &&
    ((typeof v['isSuccess']) === 'boolean') &&
    ((typeof v['isFailure']) === 'boolean') &&
    ((typeof v['allowsEntity']) === 'boolean')
  );
}
