// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { SystemConfig, isSystemConfig } from './SystemConfig';

export interface SystemConfigWrap {
  config?: SystemConfig;
  fed_config?: SystemConfig;
}

export function isSystemConfigWrap(v: any): v is SystemConfigWrap {
  return (
    (!v['config'] || (v['config'] && isSystemConfig(v['config']))) &&
    (!v['fed_config'] || (v['fed_config'] && isSystemConfig(v['fed_config'])))
  );
}
