// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface SystemRequestContent {
  policy_mode?: string;
}

export function isSystemRequestContent(v: any): v is SystemRequestContent {
  return !v['policy_mode'] || typeof v['policy_mode'] === 'string';
}
