// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface SystemConfig4Dashboard {
}

export function isSystemConfig4Dashboard(v: any): v is SystemConfig4Dashboard {
  return (
    v === {}
  );
}
