// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class SystemConfigJsonProtocol {
  private static instance: SystemConfigJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!SystemConfigJsonProtocol.instance) {
      SystemConfigJsonProtocol.instance = new SystemConfigJsonProtocol();
    }

    return SystemConfigJsonProtocol.instance;
  }
}

export const SystemConfigJsonProtocolInhabitant: SystemConfigJsonProtocol =
  SystemConfigJsonProtocol.getInstance();

export function isSystemConfigJsonProtocol(
  v: any
): v is SystemConfigJsonProtocol {
  return (
    v instanceof SystemConfigJsonProtocol &&
    v === SystemConfigJsonProtocolInhabitant
  );
}
