// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ThreatBrief {
  name: string;
  severity: string;
  application: string;
}

export function isThreatBrief(v: any): v is ThreatBrief {
  return (
    typeof v['name'] === 'string' &&
    typeof v['severity'] === 'string' &&
    typeof v['application'] === 'string'
  );
}
