// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ThreatDetails {
  id: string;
  host_name: string;
  cluster_name: string;
  count: number;
  severity: string;
  action: string;
  cap_len?: number;
  message: string;
}

export function isThreatDetails(v: any): v is ThreatDetails {
  return (
    typeof v['id'] === 'string' &&
    typeof v['host_name'] === 'string' &&
    typeof v['cluster_name'] === 'string' &&
    typeof v['count'] === 'number' &&
    typeof v['severity'] === 'string' &&
    typeof v['action'] === 'string' &&
    (!v['cap_len'] || typeof v['cap_len'] === 'number') &&
    typeof v['message'] === 'string'
  );
}
