// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ThreatDetailsData {
  threats: Array;
}

export function isThreatDetailsData(v: any): v is ThreatDetailsData {
  return (
    (v['threats'] && isArray(v['threats']))
  );
}
