// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface ThreatBriefDTO {
  name: string;
  severity: string;
  severityId: number;
  application: string;
}

export function isThreatBriefDTO(v: any): v is ThreatBriefDTO {
  return (
    typeof v['name'] === 'string' &&
    typeof v['severity'] === 'string' &&
    typeof v['severityId'] === 'number' &&
    typeof v['application'] === 'string'
  );
}
