// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ThreatBriefWrap {
  threats: Array;
}

export function isThreatBriefWrap(v: any): v is ThreatBriefWrap {
  return (
    (v['threats'] && isArray(v['threats']))
  );
}
