// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ThreatDTOWrap {
  threats: Array;
}

export function isThreatDTOWrap(v: any): v is ThreatDTOWrap {
  return v['threats'] && isArray(v['threats']);
}
