// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ThreatMajorData {
  threats: Array;
}

export function isThreatMajorData(v: any): v is ThreatMajorData {
  return (
    (v['threats'] && isArray(v['threats']))
  );
}
