// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { FiniteDuration, isFiniteDuration } from './FiniteDuration';

export interface Timeout {
  duration: FiniteDuration;
}

export function isTimeout(v: any): v is Timeout {
  return v['duration'] && isFiniteDuration(v['duration']);
}
