// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Token, isToken } from './Token';

export interface TokenWrap {
  password_days_until_expire?: number;
  token: Token;
}

export function isTokenWrap(v: any): v is TokenWrap {
  return (
    (!v['password_days_until_expire'] || ((typeof v['password_days_until_expire']) === 'number')) &&
    (v['token'] && isToken(v['token']))
  );
}
