// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface TopIncidentsDTO {
  top5Containers: Array;
  top5Nodes: Array;
  hostTotal: number;
  containerTotal: number;
}

export function isTopIncidentsDTO(v: any): v is TopIncidentsDTO {
  return (
    v['top5Containers'] &&
    isArray(v['top5Containers']) &&
    v['top5Nodes'] &&
    isArray(v['top5Nodes']) &&
    typeof v['hostTotal'] === 'number' &&
    typeof v['containerTotal'] === 'number'
  );
}
