// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface TopViolation {
  client: Array;
  server: Array;
}

export function isTopViolation(v: any): v is TopViolation {
  return (
    (v['client'] && isArray(v['client'])) &&
    (v['server'] && isArray(v['server']))
  );
}
