// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ResponseRuleID, isResponseRuleID } from './ResponseRuleID';

export interface Unquarantine {
  unquarantine: ResponseRuleID;
}

export function isUnquarantine(v: any): v is Unquarantine {
  return v['unquarantine'] && isResponseRuleID(v['unquarantine']);
}
