// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { UserBlock, isUserBlock } from './UserBlock';

export interface UserBlockWrap {
  config: UserBlock;
}

export function isUserBlockWrap(v: any): v is UserBlockWrap {
  return (
    (v['config'] && isUserBlock(v['config']))
  );
}
