// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Token, isToken } from './Token';

export interface UserToken {
  token: Token;
  roles?: { [key: string]: string };
  login_timestamp?: string;
}

export function isUserToken(v: any): v is UserToken {
  return (
    (v['token'] && isToken(v['token'])) &&
    (!v['roles'] || ((typeof v['roles']) == 'object' && Object.keys(v['roles']).every(key => ((typeof key) === 'string') && ((typeof v['roles'][key]) === 'string')))) &&
    (!v['login_timestamp'] || ((typeof v['login_timestamp']) === 'string'))
  );
}
