// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { UserProfile, isUserProfile } from './UserProfile';

export interface UserProfileWrap {
  config: UserProfile;
}

export function isUserProfileWrap(v: any): v is UserProfileWrap {
  return (
    (v['config'] && isUserProfile(v['config']))
  );
}
