// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface UserBlock {
  fullname: string;
  clear_failed_login?: boolean;
  new_password?: string;
}

export function isUserBlock(v: any): v is UserBlock {
  return (
    ((typeof v['fullname']) === 'string') &&
    (!v['clear_failed_login'] || ((typeof v['clear_failed_login']) === 'boolean')) &&
    (!v['new_password'] || ((typeof v['new_password']) === 'string'))
  );
}
