// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { User, isUser } from './User';

export interface UserWrap {
  user: User;
}

export function isUserWrap(v: any): v is UserWrap {
  return v['user'] && isUser(v['user']);
}
