// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ViolationMajorData {
  violations: Array;
}

export function isViolationMajorData(v: any): v is ViolationMajorData {
  return v['violations'] && isArray(v['violations']);
}
