// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ViolationDetailsData {
  violations: Array;
}

export function isViolationDetailsData(v: any): v is ViolationDetailsData {
  return (
    (v['violations'] && isArray(v['violations']))
  );
}
