// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { DateTime, isDateTime } from './DateTime';

export interface ViolationMajor {
  policy_id: number;
  reported_timestamp: number;
  reported_at: DateTime;
  level: string;
  client_id: string;
  client_name: string;
  client_domain: string;
  server_id: string;
  server_name: string;
  server_domain: string;
  client_ip: string;
  server_ip: string;
  server_port: number;
  applications: Array;
}

export function isViolationMajor(v: any): v is ViolationMajor {
  return (
    typeof v['policy_id'] === 'number' &&
    typeof v['reported_timestamp'] === 'number' &&
    v['reported_at'] &&
    isDateTime(v['reported_at']) &&
    typeof v['level'] === 'string' &&
    typeof v['client_id'] === 'string' &&
    typeof v['client_name'] === 'string' &&
    typeof v['client_domain'] === 'string' &&
    typeof v['server_id'] === 'string' &&
    typeof v['server_name'] === 'string' &&
    typeof v['server_domain'] === 'string' &&
    typeof v['client_ip'] === 'string' &&
    typeof v['server_ip'] === 'string' &&
    typeof v['server_port'] === 'number' &&
    v['applications'] &&
    isArray(v['applications'])
  );
}
