// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface ViolationDetails {
  cluster_name: string;
  client_image: string;
  server_image: string;
  server_port: number;
  ip_proto: number;
  servers?: Array;
  sessions: number;
  policy_action: string;
}

export function isViolationDetails(v: any): v is ViolationDetails {
  return (
    typeof v['cluster_name'] === 'string' &&
    typeof v['client_image'] === 'string' &&
    typeof v['server_image'] === 'string' &&
    typeof v['server_port'] === 'number' &&
    typeof v['ip_proto'] === 'number' &&
    (!v['servers'] || (v['servers'] && isArray(v['servers']))) &&
    typeof v['sessions'] === 'number' &&
    typeof v['policy_action'] === 'string'
  );
}
