// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { DateTime, isDateTime } from './DateTime';

export interface ViolationBrief {
  client_name: string;
  server_name: string;
  reported_at: DateTime;
}

export function isViolationBrief(v: any): v is ViolationBrief {
  return (
    typeof v['client_name'] === 'string' &&
    typeof v['server_name'] === 'string' &&
    v['reported_at'] &&
    isDateTime(v['reported_at'])
  );
}
