// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface VulContainerOutput {
  highVulsMap: { [key: string]: number };
  medVulsMap: { [key: string]: number };
  totalScannedPods: number;
  totalScannedPodsWithoutSystem: number;
}

export function isVulContainerOutput(v: any): v is VulContainerOutput {
  return (
    typeof v['highVulsMap'] == 'object' &&
    Object.keys(v['highVulsMap']).every(
      key =>
        typeof key === 'string' && typeof v['highVulsMap'][key] === 'number'
    ) &&
    typeof v['medVulsMap'] == 'object' &&
    Object.keys(v['medVulsMap']).every(
      key => typeof key === 'string' && typeof v['medVulsMap'][key] === 'number'
    ) &&
    typeof v['totalScannedPods'] === 'number' &&
    typeof v['totalScannedPodsWithoutSystem'] === 'number'
  );
}
