// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';

export interface VulnerableNodeEndpoint {
  hosts: Array;
  error?: Error;
}

export function isVulnerableNodeEndpoint(v: any): v is VulnerableNodeEndpoint {
  return (
    v['hosts'] &&
    isArray(v['hosts']) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
