// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface VulNodeOutput {
  nodeCriticalVuls: number;
  nodeHighVuls: number;
  nodeMedVuls: number;
  totalHost: number;
}

export function isVulNodeOutput(v: any): v is VulNodeOutput {
  return (
    typeof v['nodeCriticalVuls'] === 'number' &&
    typeof v['nodeHighVuls'] === 'number' &&
    typeof v['nodeMedVuls'] === 'number' &&
    typeof v['totalHost'] === 'number'
  );
}
