// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface VulnerableNodes {
  top5Nodes: Array;
  vulnerabilitiesTotal: number;
}

export function isVulnerableNodes(v: any): v is VulnerableNodes {
  return (
    v['top5Nodes'] &&
    isArray(v['top5Nodes']) &&
    typeof v['vulnerabilitiesTotal'] === 'number'
  );
}
