// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { Error, isError } from './Error';
import { WorkloadsStatus, isWorkloadsStatus } from './WorkloadsStatus';

export interface VulnerableContainerEndpoint {
  workloads: Array;
  status: WorkloadsStatus;
  error?: Error;
}

export function isVulnerableContainerEndpoint(v: any): v is VulnerableContainerEndpoint {
  return (
    (v['workloads'] && isArray(v['workloads'])) &&
    (v['status'] && isWorkloadsStatus(v['status'])) &&
    (!v['error'] || (v['error'] && isError(v['error'])))
  );
}
