// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface VulPlatformOutput {
  platformCriticalVuls: number;
  platformHighVuls: number;
  platformMedVuls: number;
}

export function isVulPlatformOutput(v: any): v is VulPlatformOutput {
  return (
    typeof v['platformCriticalVuls'] === 'number' &&
    typeof v['platformHighVuls'] === 'number' &&
    typeof v['platformMedVuls'] === 'number'
  );
}
