// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafGroupConfig, isWafGroupConfig } from './WafGroupConfig';

export interface WafGroupConfigData {
  config: WafGroupConfig;
}

export function isWafGroupConfigData(v: any): v is WafGroupConfigData {
  return v['config'] && isWafGroupConfig(v['config']);
}
