// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafSetting, isWafSetting } from './WafSetting';

export interface WafGroup {
  name: string;
  status: boolean;
  sensors: ReadonlyArray<WafSetting>;
}

export function isWafGroup(v: any): v is WafGroup {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['status']) === 'boolean') &&
    (Array.isArray(v['sensors']) && v['sensors'].every(elmt => elmt && isWafSetting(elmt)))
  );
}
