// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafSetting, isWafSetting } from './WafSetting';

export interface WafGroupConfig {
  name: string;
  status?: boolean;
  delete?: ReadonlyArray<string>;
  sensors?: ReadonlyArray<WafSetting>;
  replace?: ReadonlyArray<WafSetting>;
}

export function isWafGroupConfig(v: any): v is WafGroupConfig {
  return (
    ((typeof v['name']) === 'string') &&
    (!v['status'] || ((typeof v['status']) === 'boolean')) &&
    (!v['delete'] || (Array.isArray(v['delete']) && v['delete'].every(elmt => (typeof elmt) === 'string'))) &&
    (!v['sensors'] || (Array.isArray(v['sensors']) && v['sensors'].every(elmt => elmt && isWafSetting(elmt)))) &&
    (!v['replace'] || (Array.isArray(v['replace']) && v['replace'].every(elmt => elmt && isWafSetting(elmt))))
  );
}
