// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafGroup, isWafGroup } from './WafGroup';

export interface WafGroupsData {
  waf_groups: ReadonlyArray<WafGroup>;
}

export function isWafGroupsData(v: any): v is WafGroupsData {
  return (
    (Array.isArray(v['waf_groups']) && v['waf_groups'].every(elmt => elmt && isWafGroup(elmt)))
  );
}
