// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export class WafJsonProtocol {
  private static instance: WafJsonProtocol;

  private constructor() {}

  public static getInstance() {
    if (!WafJsonProtocol.instance) {
      WafJsonProtocol.instance = new WafJsonProtocol();
    }

    return WafJsonProtocol.instance;
  }
}

export const WafJsonProtocolInhabitant: WafJsonProtocol = WafJsonProtocol.getInstance();

export function isWafJsonProtocol(v: any): v is WafJsonProtocol {
  return (v instanceof WafJsonProtocol) && (v === WafJsonProtocolInhabitant);
}
