// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafRuleConfig, isWafRuleConfig } from './WafRuleConfig';

export interface WafRuleConfigData {
  config: WafRuleConfig;
}

export function isWafRuleConfigData(v: any): v is WafRuleConfigData {
  return (
    (v['config'] && isWafRuleConfig(v['config']))
  );
}
