// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Pattern, isPattern } from './Pattern';

export interface WafRule {
  name: string;
  id?: number;
  patterns: ReadonlyArray<Pattern>;
}

export function isWafRule(v: any): v is WafRule {
  return (
    typeof v['name'] === 'string' &&
    (!v['id'] || typeof v['id'] === 'number') &&
    Array.isArray(v['patterns']) &&
    v['patterns'].every(elmt => elmt && isPattern(elmt))
  );
}
