// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafRule, isWafRule } from './WafRule';

export interface WafRuleDetail {
  sensors: ReadonlyArray<string>;
  rules: ReadonlyArray<WafRule>;
}

export function isWafRuleDetail(v: any): v is WafRuleDetail {
  return (
    Array.isArray(v['sensors']) &&
    v['sensors'].every(elmt => typeof elmt === 'string') &&
    Array.isArray(v['rules']) &&
    v['rules'].every(elmt => elmt && isWafRule(elmt))
  );
}
