// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface WafSetting {
  name: string;
  action: string;
}

export function isWafSetting(v: any): v is WafSetting {
  return typeof v['name'] === 'string' && typeof v['action'] === 'string';
}
