// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafRule, isWafRule } from './WafRule';

export interface WafSensorConfig {
  name: string;
  comment?: string;
  change?: ReadonlyArray<WafRule>;
  delete?: ReadonlyArray<WafRule>;
  rules?: ReadonlyArray<WafRule>;
}

export function isWafSensorConfig(v: any): v is WafSensorConfig {
  return (
    ((typeof v['name']) === 'string') &&
    (!v['comment'] || ((typeof v['comment']) === 'string')) &&
    (!v['change'] || (Array.isArray(v['change']) && v['change'].every(elmt => elmt && isWafRule(elmt)))) &&
    (!v['delete'] || (Array.isArray(v['delete']) && v['delete'].every(elmt => elmt && isWafRule(elmt)))) &&
    (!v['rules'] || (Array.isArray(v['rules']) && v['rules'].every(elmt => elmt && isWafRule(elmt))))
  );
}
