// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { WafSensor, isWafSensor } from './WafSensor';

export interface WafSensorsData {
  sensors: ReadonlyArray<WafSensor>;
}

export function isWafSensorsData(v: any): v is WafSensorsData {
  return (
    Array.isArray(v['sensors']) &&
    v['sensors'].every(elmt => elmt && isWafSensor(elmt))
  );
}
