// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface Webhook {
  name: string;
  url: string;
  enable: boolean;
  type: string;
  cfg_type: string;
}

export function isWebhook(v: any): v is Webhook {
  return (
    ((typeof v['name']) === 'string') &&
    ((typeof v['url']) === 'string') &&
    ((typeof v['enable']) === 'boolean') &&
    ((typeof v['type']) === 'string') &&
    ((typeof v['cfg_type']) === 'string')
  );
}
