// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Webhook, isWebhook } from './Webhook';

export interface WebhookConfigWrap {
  config: Webhook;
}

export function isWebhookConfigWrap(v: any): v is WebhookConfigWrap {
  return v['config'] && isWebhook(v['config']);
}
