// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface WorkloadBrief2 {
  display_name: string;
  service: string;
}

export function isWorkloadBrief2(v: any): v is WorkloadBrief2 {
  return (
    typeof v['display_name'] === 'string' && typeof v['service'] === 'string'
  );
}
