// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { ScanBrief, isScanBrief } from './ScanBrief';

export interface WorkloadBrief {
  id: string;
  name: string;
  display_name: string;
  state: string;
  service: string;
  service_group: string;
  share_ns_with?: string;
  policy_mode?: string;
  domain: string;
  cap_quarantine: boolean;
  scan_summary?: ScanBrief;
  children?: Array;
}

export function isWorkloadBrief(v: any): v is WorkloadBrief {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['display_name']) === 'string') &&
    ((typeof v['state']) === 'string') &&
    ((typeof v['service']) === 'string') &&
    ((typeof v['service_group']) === 'string') &&
    (!v['share_ns_with'] || ((typeof v['share_ns_with']) === 'string')) &&
    (!v['policy_mode'] || ((typeof v['policy_mode']) === 'string')) &&
    ((typeof v['domain']) === 'string') &&
    ((typeof v['cap_quarantine']) === 'boolean') &&
    (!v['scan_summary'] || (v['scan_summary'] && isScanBrief(v['scan_summary']))) &&
    (!v['children'] || (v['children'] && isArray(v['children'])))
  );
}
