// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

export interface WorkloadsStatus {
  scanned: number;
  scheduled: number;
  scanning: number;
  failed: number;
  cvedb_version: string;
  cvedb_create_time: string;
}

export function isWorkloadsStatus(v: any): v is WorkloadsStatus {
  return (
    typeof v['scanned'] === 'number' &&
    typeof v['scheduled'] === 'number' &&
    typeof v['scanning'] === 'number' &&
    typeof v['failed'] === 'number' &&
    typeof v['cvedb_version'] === 'string' &&
    typeof v['cvedb_create_time'] === 'string'
  );
}
