// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { ScanSummary4Dashboard, isScanSummary4Dashboard } from './ScanSummary4Dashboard';

export interface WorkloadChildren {
  id: string;
  privileged: boolean;
  run_as_root: boolean;
  state: string;
  scan_summary?: ScanSummary4Dashboard;
}

export function isWorkloadChildren(v: any): v is WorkloadChildren {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['privileged']) === 'boolean') &&
    ((typeof v['run_as_root']) === 'boolean') &&
    ((typeof v['state']) === 'string') &&
    (!v['scan_summary'] || (v['scan_summary'] && isScanSummary4Dashboard(v['scan_summary'])))
  );
}
