// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';
import { ScanSummary4Dashboard, isScanSummary4Dashboard } from './ScanSummary4Dashboard';

export interface Workload {
  id: string;
  display_name: string;
  state: string;
  service: string;
  platform_role: string;
  domain: string;
  high4Dashboard?: number;
  medium4Dashboard?: number;
  scan_summary?: ScanSummary4Dashboard;
  children?: Array;
}

export function isWorkload(v: any): v is Workload {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['display_name']) === 'string') &&
    ((typeof v['state']) === 'string') &&
    ((typeof v['service']) === 'string') &&
    ((typeof v['platform_role']) === 'string') &&
    ((typeof v['domain']) === 'string') &&
    (!v['high4Dashboard'] || ((typeof v['high4Dashboard']) === 'number')) &&
    (!v['medium4Dashboard'] || ((typeof v['medium4Dashboard']) === 'number')) &&
    (!v['scan_summary'] || (v['scan_summary'] && isScanSummary4Dashboard(v['scan_summary']))) &&
    (!v['children'] || (v['children'] && isArray(v['children'])))
  );
}
