// Generated by ScalaTS 0.5.9: https://scala-ts.github.io/scala-ts/

import { Array, isArray } from './Array';

export interface Workloads {
  id: string;
  name: string;
  display_name: string;
  domain: string;
  high: number;
  medium: number;
  state: string;
  service: string;
  platform_role: string;
  children?: Array;
}

export function isWorkloads(v: any): v is Workloads {
  return (
    ((typeof v['id']) === 'string') &&
    ((typeof v['name']) === 'string') &&
    ((typeof v['display_name']) === 'string') &&
    ((typeof v['domain']) === 'string') &&
    ((typeof v['high']) === 'number') &&
    ((typeof v['medium']) === 'number') &&
    ((typeof v['state']) === 'string') &&
    ((typeof v['service']) === 'string') &&
    ((typeof v['platform_role']) === 'string') &&
    (!v['children'] || (v['children'] && isArray(v['children'])))
  );
}
